project:
  type: website

website:
  title: "Public Policy Tools for a UK Circular Economy"
  repo-url: https://github.com/OliverLysa/ce-policy
  repo-actions: [edit, issue]
    
  page-footer:
    left: 
      - text: "UKRI NICER Programme"
        href: nicer.qmd
    right: 
      - icon: info
        text: "About"
        href: about.qmd
    border: false
  back-to-top-navigation: true
  reader-mode: true
  search:
    type: textbox
    copy-button: true
    collapse-after: 2
  sidebar:
    style: "docked"
    background: "light"
    border: false
    contents:
      - index.qmd
      - section: "**Policy taxonomy**"
        contents:
         - actors.qmd
         - instruments.qmd         
         - value-drivers.qmd
         - change.qmd
      - section: "**Policy tool profiles**"
        contents:
          - no-intervention.qmd
          - voluntary-cooperative.qmd
          - information-based.qmd
          - procurement-requirements.qmd
          - consumer-rights.qmd
          - extended-producer-responsibility.qmd
          - taxes-subsidies.qmd
          - trade-policy.qmd
          - procedural.qmd
          - target-setting.qmd
          - bans-standards.qmd
          - project-level-interventions.qmd
    tools:
      - icon: house
        menu:
          - text: CE-Hub Home Page
            url:  https://ce-hub.org/
          - text: CE-Hub Knowledge Hub
            url:  https://ce-hub.org/collections/

#  navbar:
#    background: "#fcfcfc"
#    search: true
#    right:
#      - text: "Contents"
#        file: index.qmd
#      - sidebar:Taxonomy
#      - sidebar:Tools
#      - sidebar:Briefs

#  sidebar:
#    - id: Taxonomy 
#      title: "Policy taxonomy"
#      style: "docked"
#      background: "white"
#      border: false
#      contents:
#          - actors.qmd
#          - instruments.qmd         
#          - value-drivers.qmd
#          - change.qmd

#    - id: Tools
#      title: "Policy tool profiles"
#      style: "docked"
#      background: "white"
#      border: false
#      contents:
#          - no-intervention.qmd
#          - voluntary-cooperative.qmd
#          - information-based.qmd
#          - procurement-requirements.qmd
#          - consumer-rights.qmd
#          - extended-producer-responsibility.qmd
#          - taxes-subsidies.qmd
#          - trade-policy.qmd
#          - procedural.qmd
#          - target-setting.qmd
#          - bans-standards.qmd
#          - project-level-interventions.qmd
          
#    - id: Briefs
#      title: "Briefs"
#      style: "docked"
#      background: "white"
#      contents:
#          - case-reuse-repair.qmd
#          - case-recycling.qmd
#          - case-innovation.qmd
#          - case-green-finance.qmd
#          - case-community-level-support.qmd

  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
  favicon: fav.png
  open-graph: true
  page-navigation: true
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics: 
    tracking-id: "G-XHGKD5ES2C"
    anonymize-ip: true  

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: false
    footnotes-hover: true
    grid:
      sidebar-width: 220px
      body-width: 800px
      margin-width: 200px
      gutter-width: 6rem

editor: visual

margin-header: |
  ![](/logo.svg)
  
body-footer: | 
  This page brought to you by <https://ce-hub.org/>  
