---
title: "{{< fa reply >}} Responsibility-based approaches"
---

# Summary

::: {.callout-note collapse="false" appearance="simple" icon="false"}
Responsibility can be assigned to different institutional actors along the value chain by the government via a range of approaches. We look here at extended producer responsibility (EPR) - an environmental policy approach in which a producer's responsibility for a product is extended to the post-consumer stage of that product's lifecycle (OECD, 2001), as well as the wider assignment of a 'duty of care' such as on households or businesses for the correct treatment of waste.
:::

# How it works and current applications

::: {.callout-note collapse="true" appearance="simple" icon="false"}
## Extended producer responsibility schemes

Extended producer responsibility (EPR) schemes seek to enshrine the polluter pays principle[^1] by placing the physical or financial responsibility[^2] for end-of-life treatment on producers. By forcing the internalisation of those costs, this can reduce financial burdens on the public sector for waste management and potentially incentivize firms to innovate and pursue more sustainable design ([OECD, 2020](https://www.oecd-ilibrary.org/environment/improving-resource-efficiency-and-the-circularity-of-economies-for-a-greener-world_1b38a38f-en)). UK-wide producer responsibility schemes (listed [here](https://www.gov.uk/government/collections/producer-responsibility-regulations)) are already in place for packaging waste, end-of-life vehicles, batteries and accumulators and electrical and electronic equipment (EEE):

-   The **Packaging Directive** \[94/62/EC\] and **Producer Responsibility Obligations** placed requirements on eligible businesses to recover a portion of the packaging they placed on the market. This was historically operationalised in the UK through a tradable note system - Packaging waste recovery note and packaging waste recovery export note system.
-   the **End-of-Life-Vehicles Directive** \[2000/53/EC\] which required producers to introduce take-back network for vehicles to incentivise improved product design and stimulate secondary markets, while meeting targets for reuse, recycling and recovery;
-   the **Waste Electrical and Electronic Equipment Directive** (WEEE) \[2002/96/EC\] requiring producers of specific categories of electronics and electrical equipment (EEE) to register with an approved compliance scheme and pay for the costs associated with their end-of-life treatment;[^3]
-   The **Batteries and Accumulators and Waste Batteries and Accumulators Directive** \[2006/66/EC\] introduced similar material exclusion and producer responsibility requirements for batteries and accumulators while too banning residual treatment of untreated industrial components;

Reforms to these schemes are planned across the countries making up the UK to ensure producers bear the full net-cost of post-use treatment alongside the introduction of fee-modulation.
:::

[^1]: The polluter should bear the expense of carrying out pollution prevention and control measures to ensure that the environment is in an acceptable state. In other words, the costs of these measures should be reflected in the goods and services which cause pollution in production and/or consumption (OECD, 1974).

[^2]: Lindhqvist distinguishes between the following broad formats of producer responsibility schemes: 1) physical responsibility -- where a producer is involved in physical end-of-life management via take-back schemes; and 2) economic responsibility -- where a producer is made financially responsible for all or parts of the end-of-life management costs.

[^3]:
    -   **Extended producer responsibility (EPR):** The UK-wide Waste Electrical and Electronic Equipment (WEEE) Regulations 2013 place the financial responsibility for end-of-life treatment of e-waste on producers, requiring a certain level of proven treatment in line with product-category-specific collection and recovery targets. Under the regulations, distributors are also required to provide take-back systems for households. While government plans to alter the WEEE Regulations through modulating fees according to criteria of good design could contribute to making the tool a more effective driver of eco-design, it is unclear at this point if the financial incentives this gives alone will be sufficient to drive the design changes needed for longer lifespans of new products ([Milios, 2018](https://link.springer.com/content/pdf/10.1007%2Fs11625-017-0502-9.pdf); [Kunz *et al.* 2014)](https://journals.sagepub.com/doi/abs/10.1177/0008125617752694). These alterations likely need to be made alongside others such as increasing the weighting of e-waste sent for reuse in counting towards targets ([Resource Futures, 2012](http://randd.defra.gov.uk/Default.aspx?Menu=Menu&Module=More&Location=None&Completed=0&ProjectID=18116); [European Commission, 2015)](https://ec.europa.eu/environment/waste/weee/pdf/16.%20Final%20report_approved.pdf) and other tools.

::: {.callout-tip collapse="true" appearance="simple" icon="false"}
## Wider assignment of a 'duty of care'

For instance, the 'waste duty of care' ([Defra & EA, 2016](https://www.gov.uk/government/publications/waste-duty-of-care-code-of-practice#:~:text=The%20Code%20of%20Practice%20applies,businesses%20authorised%20to%20take%20it.)). Another example is the proposed responsibility placed on LAs in England to improve air quality under draft Air Quality Strategy ([Defra, 2023](https://www.gov.uk/government/publications/the-air-quality-strategy-for-england/air-quality-strategy-framework-for-local-authority-delivery)).
:::

# Performance

## Strategic fit

## Effectiveness and efficiency

## Affordability

## Long-run effects

What is the extent to which the polluter pays principle[^4] can support the preventative principle?

[^4]: The polluter should bear the expense of carrying out pollution prevention and control measures to ensure that the environment is in an acceptable state. In other words, the costs of these measures should be reflected in the goods and services which cause pollution in production and/or consumption (OECD, 1974).

While administrative data shows that the WEEE Regulations have helped enshrine the polluter pays principle, evidence of the impacts on product design is mixed (Kautto, 2006; Yu, Hills and Welford, 2008). [Gottberg et al. (2006)](https://www.ncbi.nlm.nih.gov/pubmed/16169574) - Used a literature review to develop analytical framework to explain the relationship between drivers for eco-design and the role of policies promoting EPR under the WEEE Directive (2002/96/EC). Applied framework to 8 case studies of firms from the European lighting sector. Though based on little quantitative data, which data they had seemed to suggest EPR had little effect on product development up to then as producers had been able to pass on incremental costs associated with EPR to customers with negligible effects on sales (as demand is relatively inelastic, perhaps given current prices, and given that EPR applies to all producers equally). EPR deemed unlikely to drive eco-design in the short run. Found other policies such as bans on hazardous substances, product declarations and supply chain pressures were often more effective promoters of eco-design and that a mix of policy measures required vs. reliance on economic instruments alone.

EPR fee modulation is an emerging approach ([Laubinger *et al.* 2021](https://one.oecd.org/document/ENV/WKP(2021)16/En/pdf)).

## Distributional effects

A market-correcting instrument

## Positive and negative spillovers

# Conditions for effectiveness

::: {.callout-tip collapse="true" appearance="simple" icon="false"}
## Internal and external context

Aligning our criteria with that of European countries (if they too harmonize between themselves) is desired by business and may lead to firms being more likely to design products which meet the criteria than not. For instance, the effectiveness of a modulated fee structure as introduced in France has been limited because firms were not willing to innovate for a single country's market.
:::

::: {.callout-important collapse="true" appearance="simple" icon="false"}
## Position in policy mix

Taxes and EPR, with the latter typically applied through financial responsibility, are additive in their nature.
:::

::: {.callout-caution collapse="true" appearance="simple" icon="false"}
## Design and implementation

The way the current EPR systems is set up involves firms paying into a WEEE compliance scheme based on their share of the market (in weight terms) and is a form of collective producer responsibility. From an implementation standpoint, this is practical, but firms must take back co-mingled WEEE rather than their own, meaning there are limited incentives for eco-design or investing more in products for end-of-life retrieval because the costs of doing so are private, while the benefits are shared and appropriated by competitors.The payment firms make is also not modulated in accordance with the environmental performance of the products (e.g. recyclability) they put on the market, giving limited incentive to alter the products they sell beyond reducing weight (assuming the costs are viewed as materially sufficient to alter production practices at all).

In addition, while firms are required to take some physical responsibility for the amount of waste generated, at the point of doing so, this is co-mingled with the WEEE of other producers, meaning that EEE generated by one firm will not find its way back to that specific producer, meaning that investments into the product e.g. using more durable or valuable materials, will be appropriated by actors other than the producers themselves.  While costs of treatment are covered, the signal to improve eco-design is relatively weak through EPR. [Milios (2018)](https://link.springer.com/content/pdf/10.1007%2Fs11625-017-0502-9.pdf) and [Kunz *et al.* (2014)](https://journals.sagepub.com/doi/abs/10.1177/0008125617752694).

2012 review by the Individual Producer Responsibility Working Group into introduction of individual producer responsibility in the UK recommends: drivers of eco-design are strengthened when individual producers are made directly responsible for total end-of-life costs. Altering the WEEE Directive's current 'collective producer responsibility' approach by modulating responsibility according to criteria of good design (as a proxy for end-of-life treatment) might make the tool a more effective driver of eco-design.

[HP](http://h20195.www2.hp.com/V2/GetPDF.aspx/c04297138.pdf) - Important to consider EPR in context of waste having a value. Might involve returning fees to producers if a profit is made on the product -- would act as an additional source of incentive potentially as a firm doesn't only reduce it's obligations, but can actively make money from resale of the products if their WEEE does have value.- 2012 review by the Individual Producer Responsibility Working Group into introduction of individual producer responsibility in the UK recommends: drivers of eco-design are strengthened when individual producers are made directly responsible for total end-of-life costs, however reverse logistics of producers collecting their own waste is viewed as impractical. Therefore modulating fees can be an effective middle-ground.

Fee modulation criteria, doesn't need to include anything which is legally mandated within the modulated fees. Eco-design standards remove the most egregious problems with WEEE, while modulated fees (if the cost is sufficiently high) can be used to incentivize better environmental performance.
:::

# Future applications in UK CE framework

::: {.callout-tip .g-col-10 collapse="true" appearance="minimal" icon="false"}
## {{< fa pen-ruler >}} **Reconfigure**

Reconfigure Given challenges faced by modulated EPR, it might be viewed as best as a policy experiment on improving EPR and the drivers of eco-design more broadly ([Lifset *et al.* 2023](https://doi.org/10.1016/j.wasman.2023.05.033)).
:::

::: {.callout-important .g-col-10 collapse="true" appearance="minimal" icon="false"}
## {{< fa arrows-left-right >}} **Extend**

In England, Defra have committed to consulting on the introduction of the EPR policy approach for five new additional product groups: textiles; bulky waste such as mattresses and furniture; vehicle tyres; fishing gear and certain materials used in the construction and demolition sector.
:::
