# UKRI NICER Programme

The UKRI National Interdisciplinary Circular Economy Research (NICER) Programme is a four-year £30 million investment to deliver research, innovation, and the evidence base needed to move towards a more resilient UK circular economy. The programme is made up of five Circular Economy Research Centres (CECs) each focused on a speciality material flow alongside a coordinating CE-Hub:

-   [The Textiles Circularity Centre (TCC)](https://ce-hub.org/textiles-circularity-centre/), led by the Royal College of Art;

-   [The Interdisciplinary Circular Economy Centre for Mineral-based Construction Materials (ICEC-MCM)](https://ce-hub.org/centre-for-mineral-based-construction-materials/),  led by UCL;

-   [The National Interdisciplinary Centre for the Circular Chemical Economy (CircularChem)](https://ce-hub.org/centre-for-circular-chemical-economy/),  led by Loughborough University;

-   [The Interdisciplinary Circular Economy Centre for Technology Metals (Met4Tech)](https://ce-hub.org/centre-for-technology-metals/),  led by the University of Exeter;

-   [The Interdisciplinary Centre for Circular Metals (CircularMetal](https://ce-hub.org/centre-for-circular-metals/)), led by Brunel University London; and

-   [The National Interdisciplinary Circular Economy Research Hub (CE-Hub)](https://ce-hub.org/circular-economy-hub-ce-hub/),  led by the University of Exeter.
