---
title: "{{< fa basket-shopping >}} Procurement"
---

# Summary

::: {.callout-note collapse="false" appearance="simple" icon="false"}
Approximately £300 billion is spent each year in the UK on public procurement and public authorities can therefore exercise significant demand-side leverage on the market as a large purchaser. Government consumption expenditure accounted for approximately 10% of England's material footprint (77 Mt) in 2019 ([Defra, 2023](https://www.gov.uk/government/statistics/englands-material-footprint/englands-material-footprint#footprint-by-end-use)), and a similar percentage for the UK as a whole.

Circular procurement, as part of a wider 'green public procurement' involves public authorities intentionally procuring goods and services aligned with circular economy principles and with a reduced environmental impact relative to alternatives ([CSCP,](https://www.cscp.org/circular-procurement/#:~:text=Put%20simply%2C%20circular%20procurement%20is,strategy%20of%20a%20particular%20organisation.)). It is a economic-based consumption-side or inflow oriented approach.

Improved public procurement guidance and requirements in line with circular economy criteria can also play a role given the significant demand-side leverage the Government can exert as a larger purchaser. This can provide a direct financial incentive to firms to develop more durable products while also bringing innovation spillovers. Procurement changes can be implemented in a variety of ways, with Sweden for instance, having put in place public procurement requirements for refurbished ICT equipment across its municipalities ([Crawford *et al.* 2018)](https://www.sciencedirect.com/science/article/pii/S2212827118304979).
:::

# How it works and current applications

'Green public procurement' (GPP) is 'a process where public authorities seek to procure goods, services and works with a reduced environmental impact throughout their life-cycle when compared to goods, services and works with the same primary function that would otherwise be procured' ([European Commission, 2008)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52008DC0400). It works as a demand-pull measure at the market formation and diffusion stages along the technological/innovation lifecycle so as to increase the size of a market for a new technology and like other forms of niche market creation, information & labelling approaches, scrappage schemes, subsidy schemes and minimum standards mandates (Newet 2009; Foxon et al. 2005; Goodward et al. 2011).

There are a range of sustainable procurement applications already in use in the UK including:

-   The Public Services (Social Value) Act 2012 (the 'Social Value Act', or SVA) which requires consideration of how procurement might improve economic, social and environmental wellbeing;

-   The 'Greening Government Commitments' to buy more sustainable and efficient products and services across the government estate;

-   The 'Procuring for Growth Balanced Scorecard' permitting non-financial considerations in major project procurements;

-   Individual government department procurement requirements such as those of HMRC; and

-   Delivering on the 'greening government' commitment by removing single-use packaging from government estates.

Certain government departments e.g. HMRC already have their own sustainable procurement requirements, but across the UK government, procurement rules are largely fragmented.

# Performance

## Strategic fit

There are a range of sustainable procurement applications already in use in the UK, indicating a high level of strategic fit in some areas and in some forms.

## Effectiveness and efficiency

Modelling studies have indicated potential effectiveness. A 2009 study by WRAP and the Stockholm Environment Institute (SEI) examined the potential of 14 resource efficiency strategies, including altered public sector procurement.

A study by ERM (2011) found few policies or government initiatives in the UK had lifetime extension as their primary aim, a finding echoed in a more recent 2016 assessment of policies across the EU by Montvalo, Peck and Rietveld. ERM worked from the basis that an assessment of generics impacts of lifetime extension policies across groups of products may prove problematic and focus instead on 13 measures applied across different shortlisted products that are viewed as having greatest potential for lifetime extension. As an example, voluntary product durability standards, mandatory durability declarations and extended warranties were considered as potentially effective ways to extend the lifespans of washing machines, while Enhanced Capital Allowances (ECAs) and green public procurement were identified as suitable measures for extending the lifespan of laptops.

An example of effective green procurement requirements is the Energy Star programme in the USA which aimed to improve energy efficiency in over 35 product categories, with its success partly linked to them being introduced in a context of the threat of more stringent energy standards being put in place. Sweden have put in place public procurement requirements for refurbished ICT equipment in Swedish municipalities with the potential to drive demand for reused products, associated certification and also then supply of reused/refurbishment products ([Crawford *et al.* (2018)](https://www.sciencedirect.com/science/article/pii/S2212827118304979).

## Affordability

Cost in relation to BAU.

## Long-run effects

Provides a direct financial incentive to firms to develop more e.g. durable products while encouraging innovation which can indirectly support development of more durable/less quickly obsolete EEE.

## Distributional effects

## Positive and negative spillovers

# Conditions for effectiveness

[Ghose and Kapur (2019)](https://t20japan.org/wp-content/uploads/2019/03/t20-japan-tf3-7-business-models-efficiency-circular-economy.pdf) in a study of government policies and practices to enable business models for resource efficiency and a circular economy proposed countries: 1) incentivising circular busines models through improving access to finance, the provision of tax incentives and subsidies, integrating resource efficiency criteria in procurement policies and practices and enabling industrial symbiosis.

# Design and implementation considerations

# Prospective applications in UK CE framework

Approaches to strengthen the role of procurement across the UK include guidance on how to use criteria to create more circular outcomes, provision of training to public procurers, through the technical specification related to the contract for goods and services, or in the award criteria ([European Parliament, 2017)](http://www.europarl.europa.eu/RegData/etudes/STUD/2017/602065/IPOL_STU(2017)602065_EN.pdf).

In 2015, Italy spent 4 billion euros on green purchases by public administrations (x4 that in 2010). Initially introduced voluntarily guidelines, while applying green criteria to public procurement is now mandatory.

Procurement rules can further incentivise uptake of voluntary agreements. Marketing benefits from participation increase participant numbers in a programme e.g. the Energy Star programme has been made more effective by US Government procurement rules.
