---
title: "{{< fa building >}} Project-level & public sector delivery"
---

# Summary

::: {.callout-note collapse="false" appearance="simple" icon="false"}
Governments across the UK generally no longer hold the same means of production via state enterprises as they did in the past. Project-level and national delivery nevertheless remain tools for influence in some areas. Here, we cover project-level interventions and public sector delivery, referring to instances where the government funds specific projects or programmes out of its budget as a form of collective consumption and investment.
:::

# How it works and current applications

Project- and programme-level support & public sector delivery refers to instances where the government funds specific projects or programmes out of its budget as a form of collective consumption and investment. This is made possible through revenues generated by the government, primarily from taxes paid in the UK and a small percentage (\~10%) from non-tax sources, including income received from public corporations and interest payments on government assets ([IFS](https://ifs.org.uk/taxlab/taxlab-key-questions/where-does-government-get-its-money#:~:text=The%20government%20raises%20around%20%C2%A3,contributions%20(NICs)%20and%20VAT.)).

::: {.callout-note collapse="true" appearance="simple" icon="false"}
## Project-level support

We cover grants and loans here as well as in-kind resourcing.

-   Offshore Wind Component Technologies Development and Demonstration Scheme - https://www.gov.uk/government/publications/offshore-wind-component-technologies-development-and-demonstration-scheme
-   Energy Savings Opportunities Scheme
-   Fund the £20 million Plastics Innovation fund, the £20 million Plastic and Waste Investment Fund and R&D through Plastics Pact
-   Identifies one-off upfront CAPEX support for low-carbon steel processing infrastructure ([Energy Transitions Commission, 2023](https://www.energy-transitions.org/wp-content/uploads/2023/04/Unlocking-the-First-Wave-of-Breakthrough-Steel-Investments-International-Opportunities-April-2023.pdf)).
-   The Consistency Reforms policy will extend Local authorities' responsibilities while EPR will help fund the expanded capability to collect packaging waste.
-   £4 million funded project by UKRI to develop an automated sorting and recycling demonstrator plant for the UK in textiles
-   English local retrofit schemes: Local Authority Delivery, Home Upgrade Grant and the Social Housing Decarbonisation Fund ([Dyson, 2023](https://www.e3g.org/wp-content/uploads/Locally-led-retrofit-executive-summary.pdf))
-   [Independent Review of the UK's Research, Development and Innovation Organisational Landscape](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1141484/rdi-landscape-review.pdf)
-   [Review of Defra funding for Wrap](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/255512/wrap-funding-review-summary-responses-131104.pdf)
-   [Salix](https://www.savemoneycutcarbon.com/sustainability-services/funding/public-sector-financing/#:~:text=Salix%20Finance%20is%20an%20independent,and%20replacing%20dated%20inefficient%20technologies.)

Competitive market-based bid programmes
:::

::: {.callout-tip collapse="true" appearance="simple" icon="false"}
## Public-sector delivery
:::

While the state retains an important role in supporting the market and innovation (Castree, 2008) and state spending as a percentage of GDP has grown in the last century, shifts in UK Government's power and activity away from it as a producer, associated growth of privatisation and New Public Management approaches, has led in many cases to an externalisation of prior state functions (Swyngedouw, 2005).

# Performance

## Strategic fit

## Effectiveness and efficiency

Solid waste management makes up the largest proportion of all UK government environmental protection expenditure, comprising £11.6 billion in 2019 of a total expenditure of £14.4 billion (ONS, 2021). Solid waste management also made up the largest proportion of business environmental protection expenditure in 2019, comprising between £0.68 and £1.04 billion (0.9 billion central estimate). The majority of business expenditure on solid waste management (86%) related to external (i.e. not in-house) operating expenditure (ONS, 2020).

## Affordability

The UK Labour party has committed to increasing public spending on green technology to £28bn a year by 2030 if elected, however doing so would be made more difficult by the constrained fiscal context ([Zenghelis, 2023](https://www.bennettinstitute.cam.ac.uk/blog/clean-transition/)).

## Long-run effects

## Distributional effects

## Positive and negative spillovers

Targeted public spending can play a key role in galvanising public investment in areas of necessary infrastructure.

Studies have shown fiscal austerity since the 2008 Financial Crisis limited the effects of productivity-generating government investment and increased government debt to GDP as a ratio ([Jordá and Taylor, 2016](https://doi.org/10.1111/ecoj.12332)). Zenghelis (2023) argues 'the safest way to restore health to \[UK\] public finances is to target specific investment in properly measured assets that generate economies of scale in production and discovery, and drive long-term growth.'

At the same time, under certain conditions government spending can also have crowding out effects.

# Conditions for effectiveness

## Design and implementation considerations

# Future applications in UK CE framework

"The use of targeted public finance -- such as through the UK Infrastructure Bank -- could also play a critical role in attracting private investment in much needed infrastructure to support greater rates of recycling, repair, remanufacturing and re-use." ([Aldersgate, 2021](https://www.aldersgategroup.org.uk/publications/post/englands-resource-efficiency-agenda-must-be-accelerated-with-urgency/)).

::: {.callout-note collapse="true" appearance="simple" icon="false"}
## {{< fa magnifying-glass-plus >}} Spotlight on innovation

The direction technological change drives environmental impact is disputed. One one hand, some suggest that technological change will likely always contribute to increased environmental use and degradation (Commoner, ), or that rates of technological change are likely to be insufficient to offset environmental impacts driven by growing and more affluent populations. On the other, some argue that technological progress is a primarily positive influence and can grow at a sufficient rate to offset the impacts of growing populations and rising affluence (Kneese and Ridker, 1972; Nordhaus, 1973; Solow, 1973).

The UK stood in the top 10 for per capita patent applications in 2021 ([EPO, 2022](https://www.epo.org/news-events/press/releases/archive/2022/20220405.html)).

Nevertheless, innovation in certain forms can support ambitions to move towards a more circular economy, particularly when driven in conjunction with broader environmental policies parameterising the direction of that change. Innovation at the product, process and system-level under certain conditions have the potential to help (reduce the costs of) delivering long-term improvement in our treatment of resources and waste, thereby heightening the importance of improving framework conditions for eco-innovation (Bleischwitz, 2008; Grubb and Wieners, 2020).Technology change and innovation systems.

All technologies dominant today began as inventions through basic research & development (R&D) and thereafter: emerged as innovations through applied R&D; entered or became niche markets through investment and learning-by-doing; diffused more widely via mass production and standardisation; and may at some point become obsolete as new technologies emerge. The length of this life-cycles can vary by the technology in question, is not always unidirectional and in today's global economy, frequently occurs across different geographies.

Technical and price dimensions are crucial determinants of technological change (Nemet, 2009). As technologies move from innovation stages and getting a footing in the economy, dynamics can work to either limit or accelerate their uptake and entrenchment (negative or positive feedbacks, respectively). Positive feedback effects across both production and consumption sides include (Sanden and Azar, 2005):

1.  Scale effects - the average unit costs of production (including through more distributed R&D) falling due to economies of scale which can allow prices to fall;

2.  Learning effects - cost reductions arising through experience gained in historical production and through 'learning by doing' by consumers; and

3.  Network effects - benefits derived by another's use of the same technology, including the development of network infrastructure supporting particular technologies such as petrol stations for internal combustion engine vehicles.

At the same time, the relative absence of these effects for new technologies can act to slow or block their further progression through the technology lifecycle, even where an innovation might be quality-improving or increase the bottom line of producers and consumers over a longer time frame. Behavioural and institutional negative feedback effects can also contribute to nullifying change and lead to continuity in existing socio-technical regimes (Wells and Niuwenhuis, 2012). These can include:

1.  Public and private institutions seeking to maintain the status quo due to vested interests and \[perceived\] core rigidities (e.g. those found in the UK electricity sector to wider renewable deployment (Geels, 2014));

2.  The development of preferences, trust and familiarity which discourage exploration of alternatives (Nelson and Winter, 1977);

3.  Policies, such as those which have specified particular technologies or block the development of alternatives in other ways such as subsidies. A widely referred to example is the Waste Framework Directive's definitions of waste and end of waste; and

4.  Other institutional lock-in effects, such as specifications within long-term local authority waste management contracts with private organisations which are difficult to alter (Iacovidou, 2019).

Switching costs can take several forms. For economies of scale, changing products become relatively more expensive the higher the quantity that has already been produced. For network effects, consumers bear costs through decreased utility once new products are introduced, and for learning effects, the benefits from having learnt in previous production will be lost once a new product is produced.

The result of these negative feedback effects to new technologies, where they actually exist, is that socio-technical change is frequently characterised by long periods of stability around specific technologies, shifts in which occur incrementally (such as through optimisation or partial system redesign) over time (Wetterings et al. 1997). In a study of past energy transitions in the UK, Fouquet (2010) found the stage of technological diffusion taking at least 50 years and the whole innovation cycle taking 100 years, with change typically towards cheaper inputs and longer-term antecedents frequently at play.

The technology innovation-systems framing recommends that innovation is addressed in a systemic way and that incentive structures are aligned e.g. demand-pull and technology-push policies deployed strategically in combination due to a danger of becoming locked-into "suboptimal" technologies through reliance on demand-pull strategies alone (Sandén and Azar, 2005).

Policies required to drive change across various levels can be categorised into:

1.  ***Technological-push:*** Technology-specific policies proponents argue that general policy instruments mainly benefit already commercially available technologies, whereas technology specific policies such as standards, but too R&D, demonstration, niche market creation and network support are required to stimulate various product and process innovation that can boost immature technologies (Bergek and Berggren, 2014). Needed to resolve market failures relating to innovation, including adoption externalities, knowledge, externalities and incomplete information. Work by stimulating the supply of new technology through policy for minimum standards, innovation grants to higher-education institutes, tax credits for private R&D, supporting early-stage deployment (important when there are other market failures e.g. learning spillovers) demonstration projects, appropriable patents to overcome positive externalities as a form of market failure undermining technological development, knowledge exchange, education & training;

2.  ***Demand-pull*** --- So as to increase the size/strength of the market for new technology via public procurement rules, behaviour change, information & labelling, scrappage schemes to swiften fleet turnover, subsidy schemes for plug-in electrics, quantity-based mechanisms, regulation and mandates, minimum standards and price-based mechanisms (Newet 2009). While near-term targets can be met by economy wide instruments such as taxes, technology specific policies are needed to bring new technologies to the shelf, without which stricter long-term targets may not be so easily met (Sandén and Azar, 2005).

3.  ***Environmental policies*** are needed to support technologies which might increase environmental quality but which suffer from market failures e.g. due to environmental improvements not being priced in the market (so taxes or financial incentives might be needed to complete the market and create its associated incentives) (Jaffe *et al.* 2005; van den Bergh, 2013). Environmental policies include pricing natural capital properly through addressing environmental externalities via regulation, and increasing the price of dirty products, processes and services, and removing distortionary subsidies (Hepburn, Pless and Popp, 2018).

Government policies can focus on different stages of the innovation process: 1) at the Research Stage e.g. providing grants; 2) at the Demonstration Stage  e.g. using commercial scale pilots; 3) for Market Formation Stages e.g. public procurements; and 4) for the Diffusion Stage e.g. price or quantity mechanisms (Foxon et al. 2005; Goodward et al. 2011). The right policy mix for innovation at certain times is critical (Kivimaa and Kern, 2016). At the technological risk stage there is a need for technology push policies, while at the commercial risk stage, a need for demand-pull through policies. The appropriate mix for driving innovation depends on the policies, economic, and social context and applicable market failures. Technology supply and demand-pull instruments are often required across the technology lifecycle to support innovation. Learning, upscaling and building societal support play important softer roles (Nemet, Zipperer and Kraus, 2018).

Policies supporting the supply of innovation include intellectual property (IP) protection, funding laboratory and testing infrastructure, training and skills development, university-industry collaborations, formal and informal mechanisms of knowledge exchange, in addition to introducing roadmaps to guide innovation and financial incentives e.g. tax cuts. Policies supporting demand for innovation include supporting demonstration projects, altering public procurement rules, niche market creation and the creation of incentives e.g. price floors, with policy across both supply and demand dynamics influential at each stage of the innovation process and at the system level.

Government interventions can focus across these levels and the stages of technology lifecycles outlined to drive change. However, there can also be risks to government steering e.g. locking-in sub-optimal technologies which can be diffcult to avoid in cases of capital assets, or high transition costs. Different instruments and approaches can be applied required furthermore, with there being relative strengths and weaknesses of instruments. For instance, while technology standards involve choosing technology 'winners', they can also swiften and subsidise firm-level R&D. Technology supply and demand-pull instruments are often required across the technology lifecycle to support innovation. Learning, upscaling and building societal support play important softer roles (Nemet, Zipperer and Kraus, 2018).

Innovation can be characterised as being:

1.  Incremental - with modification of existing products and processes at the margins e.g. slight improvements in camera resolution of smartphones; or

2.  Radical - with more extensive shifts in products and processes affecting multiple parts of the economy.

Radical shifts in socio-technical systems have been effectively called for to achieve 'net zero' in the UK and to remain in line with 1.5-2 degrees of warming globally (IPCC, 2021). The same can be said for many visions of shifting towards a more circular economy, with the necessary scale and pace of transition argued to need to be transformational (Potochnik *et al*. 2022). Simms (2019) argues that there are many examples of rapid systemic achieved in tight timescales. For instance, rail expansion in the UK in the mid-1800s, with 4,400 miles of train track laid in just 7 years and the mobilisation around WW2.

Achieving swift and systemic innovations increases the necessity of having actors involved with the capacity to influence the market and society, who can destabilise existing regimes and tilt factors in favour of change - typically government actors (Smith et al. 2010; Arranz, 2017). Mazzucato (2015) nots that major technological shifts have been achieved in the past through concerted government effort including dedicated research funding, infrastructural investment and setting national direction.
:::
