---
title: "**Catalogue of evidence sources**"
---

Abbott, A., Nandeibam, S. and O'Shea, L. (2011). Explaining the variation in household recycling rates across the UK. *Ecological Economics*, 70(11), pp.2214--2223. doi:https://doi.org/10.1016/j.ecolecon.2011.06.028.

Abbott, K. and Snidal, D. (2009). The Governance Triangle: Regulatory Standards Institutions and the Shadow of the State. In Whose Benefit? Explaining Regulatory Change in Global Politics (Walter Mattli & Ngaire Woods, eds.).

‌Abbott, K.W. (2012). The Transnational Regime Complex for Climate Change. *Environment and Planning C: Government and Policy*, \[online\] 30(4), pp.571--590. doi:https://doi.org/10.1068/c11127.

‌Abu-Bakar, H. (2023). *Navigating the Path to Circularity: A Guide to Circular Economy Roadmaps*. \[online\] Available at: <https://ce-hub.org/knowledge-hub/navigating-the-path-to-circularity-a-guide-to-circular-economy-roadmaps/> \[Accessed 2 Nov. 2023\].

Aguilar-Hernandez, G.A., Sigüenza-Sanchez, C.P., Donati, F., Rodrigues, J.F.D. and Tukker, A. (2018). Assessing circularity interventions: a review of EEIOA-based studies. *Journal of Economic Structures*, 7(1). doi:https://doi.org/10.1186/s40008-018-0113-3.

Aldersgate (2021). Closing the loop: Time to crack on with resource efficiency. Available at: <https://www.aldersgategroup.org.uk/publications/post/closing-the-loop-time-to-crack-on-with-resource-efficiency/> \[Accessed 27 Nov. 2023\]

Alcott, B. (2005). Jevons' paradox. *Ecological Economics*, 54(1), pp.9--21. doi:https://doi.org/10.1016/j.ecolecon.2005.03.020.

Ambec, S. and Lanoie, P. (2008). Does It Pay to Be Green? A Systematic Overview. *Academy of Management Perspectives*, \[online\] 22(4), pp.45--62. Available at: <https://www.jstor.org/stable/27747478>.

Arkova, A., Anchen, J., Ajit, V., Schmidt, A., Stolz, P., Wittbjer, T. (2023). What goes around comes around: Insuring the circular economy. *Swiss Re Institute*.

Barbier, E.B. (2015). *Nature and Wealth*. *Palgrave Macmillan UK eBooks*. doi:https://doi.org/10.1057/9781137403391.

Barnatt, J. and Penny, R., (2004). *The Lead Legacy. The prospects for the Peak District's Lead Mining Heritage.* English Heritage and English Nature.

Baptist, S. and Hepburn, C. (2013). Intermediate inputs and economic productivity. *Philosophical Transactions of the Royal Society A: Mathematical, Physical and Engineering Sciences*, 371(1986), p.20110565. doi:https://doi.org/10.1098/rsta.2011.0565.

Barbrook-Johnson, P. and Penn, A.S. (2022). *Systems Mapping*. Cham: Springer International Publishing. doi:https://doi.org/10.1007/978-3-031-01919-7.

Bauer, T., Busch, P., and Tuncer, B. (2023). Reducing plastic waste through voluntary instruments. Learning from the EU Green Deal implementation. Kielce, Poland: EPRD Ltd.

Berestycki, C. and Dechezleprêtre, A. (2020). *Assessing the efficiency of environmental policy design and evaluation: Results from a 2018 cross-country survey*. \[online\] OECD iLibrary. Available at: <https://www.oecd-ilibrary.org/economics/assessing-the-efficiency-of-environmental-policy-design-and-evaluation-results-from-a-2018-cross-country-survey_482f8fbe-en>.

Blackman, A., Afsah, S. and Ratunanda, D. (2004). How Do Public Disclosure Pollution Control Programs Work? Evidence from Indonesia. *Human Ecology Review*, \[online\] 11(3), pp.235--246. Available at: https://www.jstor.org/stable/24707717 \[Accessed 2 Nov. 2023\].

Bleischwitz, R. (2010). International economics of resource productivity -- Relevance, measurement, empirical trends, innovation, resource policies. *International Economics and Economic Policy*, 7(2-3), pp.227--244. doi:https://doi.org/10.1007/s10368-010-0170-z.

Bloodworth, A. (2014). A once and future extractive history of Britain. Pp 1-6 in Hunger, E., Brown, T. J. and Lucas, G. (Eds.) Proceedings of the 17th Extractive Industry Geology Conference, EIG Conferences Ltd.

Bringezu, S. (2015). Possible Target Corridor for Sustainable Use of Global Material Resources. *Resources*, 4(1), pp.25--54. doi:https://doi.org/10.3390/resources4010025.

British Ecological Society (2017) An introduction to policy in the UK: Policy guide. Available at: <https://www.britishecologicalsociety.org/wp-content/uploads/2017/05/An-introduction-to-policymaking-in-the-UK.pdf>

Broadberry, S., Campbell, B.M.S., Klein, A., Overton, M. and van Leeuwen, B. (2015). *British Economic Growth, 1270--1870*. \[online\] *Cambridge University Press*. Cambridge: Cambridge University Press. Available at: https://www.cambridge.org/core/books/british-economic-growth-12701870/A270234C137117C8E0F1D1E7E6F0DA56.

‌Bryant, R.L. and Bailey, S. (1997). *Third world political ecology*. Routledge.

Cambridge Institute for Sustainable Leadership (2022). New poll indicates strong business appetite for net zero regulation. Available at: <https://www.cisl.cam.ac.uk/news/new-poll-indicates-strong-business-appetite-net-zero-regulation>

Castree, N. (2008). Neoliberalising Nature: The Logics of Deregulation and Reregulation. *Environment and Planning A: Economy and Space*, 40(1), pp.131--152. doi:https://doi.org/10.1068/a3999.

CCD (2022). Circular Cities Declaration Report 2022. Available at: <https://circularcitiesdeclaration.eu/fileadmin/user_upload/CCD-Report-2022.pdf>

Coase, R.H. (1960). The Problem of Social Cost. *The Journal of Law & Economics*, \[online\] 3, pp.1--44. Available at: <https://www.jstor.org/stable/724810>.

Circle Economy (2019). The Role of Municipal Policy in the Circular Economy. Available at: <https://circulareconomy.europa.eu/platform/sites/default/files/5d15be02940ad0c394e7a9ff_circle_economy_-_the_role_of_municipal_policy_in_the_circular_economy.pdf>

Clarkson, M.B.E. (1995). A Stakeholder Framework for Analyzing and Evaluating Corporate Social Performance. *The Academy of Management Review*, 20(1), pp.92--117.

Climate Change Committee (2020). Sixth Carbon Budget. Available at: <https://www.theccc.org.uk/publication/sixth-carbon-budget/> \[Accessed 2 Nov. 2023\].

Cole, C., Cooper, T. and Gnanapragasam, A. (2017). Extending product lifetimes through WEEE reuse and repair: Opportunities and challenges in the UK. Presented at the Electronics Goes Green 2016+ (EGG), Berlin, 6-9 Sept. 2016.

Cooper, A.H., Brown, T.J., Price, S.J., Ford, J.R. and Waters, C.N. (2018). Humans are the most significant global geomorphological driving force of the 21st century. *The Anthropocene Review*, 5(3), pp.222--229. doi:https://doi.org/10.1177/2053019618800234.

Couto, L.C. (2023). How to boost international private climate finance. Available at: <https://www.chathamhouse.org/2023/04/how-boost-international-private-climate-finance/03-role-central-banks-and-financial>

Crafoord, K., Dalhammar, C. and Milios, L. (2018). The use of public procurement to incentivize longer lifetime and remanufacturing of computers. *Procedia CIRP*, 73, pp.137--141. doi:https://doi.org/10.1016/j.procir.2018.03.316.

Cramer, J. (2017). The Raw Materials Transition in the Amsterdam Metropolitan Area: Added Value for the Economy, Well-Being, and the Environment. *Environment: Science and Policy for Sustainable Development*, 59(3), pp.14--21. doi:https://doi.org/10.1080/00139157.2017.1301167.

‌Dasgupta, P. *et al.* (2021). Final Report - The Economics of Biodiversity: The Dasgupta Review. HM Treasury.

del Rio, P. and Howlett, M.P. (2013). Beyond the 'Tinbergen Rule' in Policy Design: Matching Tools and Goals in Policy Portfolios. *SSRN Electronic Journal*. doi:https://doi.org/10.2139/ssrn.2247238.

Department for Environment, Food & Rural Affairs (2018a). Resources and Waste Strategy.

Department for Environment, Food & Rural Affairs (2018b). Resources and Waste Strategy: Evidence Annex.

Department for Environment, Food & Rural Affairs (2023a). *ENV23 - UK statistics on waste*. \[online\] Available at: <https://www.gov.uk/government/statistical-data-sets/env23-uk-waste-data-and-management>.

Department for Environment, Food & Rural Affairs (2023b). *England's Material Footprint*. \[online\] Available at: <https://www.gov.uk/government/statistics/englands-material-footprint/englands-material-footprint>.

Department for Environment, Food & Rural Affairs (2023c). *Fly-tipping statistics for England*. \[online\] Available at: <https://www.gov.uk/government/statistics/fly-tipping-in-england>.

Department of the Environment, Climate and Communications (2021). Whole of Government Circular Economy Strategy 2022 -- 2023 'Living More, Using Less'

Dittrich, M., Giljum, S., Lutter, S., Polzin, C. (2012). Green Economies around the World? Implications of Resource Use for Development and the Environment; SERI: Vienna, Austria. Available at: <https://www.boell.de/en/content/green-economies-around-world-implications-resource-use-development-and-environment> 

‌Duit, A. (2014). *State and Environment*. \[online\] *The MIT Press eBooks*. doi:https://doi.org/10.7551/mitpress/9780262027120.001.0001.

Dye, T.R. (1972). Policy analysis and political science: some problems at the interface. *Policy Studies Journal*, 1(2), pp.103--107. doi:https://doi.org/10.1111/j.1541-0072.1972.tb00077.x.

Eales, J., Bethel, A., Galloway, T., Hopkinson, P., Morrissey, K., Short, R.E. and Garside, R. (2022). Human health impacts of exposure to phthalate plasticizers: An overview of reviews. *Environment International*, 158, p.106903. doi:https://doi.org/10.1016/j.envint.2021.106903.

EEA (2018). *Resource efficiency --- European Environment Agency*. Available at: <https://www.eea.europa.eu/airs/2018/resource-efficiency-and-low-carbon-economy/resource-efficiency>

Ekins, P., Domenech, T., Drummond, P., Bleischwitz, R., Hughes, N. and Lotti, L. (2019). "The Circular Economy: What, Why, How and Where", Background paper for an OECD/EC Workshop on 5 July 2019 within the workshop series "Managing environmental and energy transitions for regions and cities", Paris.

Elhacham, E., Ben-Uri, L., Grozovski, J., Bar-On, Y.M. and Milo, R. (2020). Global human-made mass exceeds all living biomass. *Nature*, \[online\] 588, pp.442--444. doi:https://doi.org/10.1038/s41586-020-3010-5.

Ellen MacArthur Foundation. (n.d.). Regenerative food production. Available at: <https://www.ellenmacarthurfoundation.org/regenerative-food-production>

Ellen MacArthur Foundation. (n.d.). Plastics and the circular economy -- deep dive. Available at: <https://www.ellenmacarthurfoundation.org/plastics-and-the-circular-economy-deep-dive>

Ellen MacArthur Foundation. (2015). Towards a circular economy: Business rationale for an accelerated transition. Available at: https://www.ellenmacarthurfoundation.org/towards-a-circular-economy-business-rationale-for-an-accelerated-transition

Ellen MacArthur Foundation. (2019). Circular economy in cities: Policy levers. Available at: <https://www.ellenmacarthurfoundation.org/policy-levers>

Ellen MacArthur Foundation. (2021). Universal circular economy policy goals. Available at:<https://www.ellenmacarthurfoundation.org/universal-policy-goals/overview/>

Environment Agency. (2021). National waste crime survey report 2021: findings and analysis. Available at: <https://www.gov.uk/government/publications/national-waste-crime-survey-report-2021-findings-and-analysis> \[Accessed 28 Nov. 2023\]

Ettlinger, S. (2022). Aggregates Levy in the United Kingdom. Eunomia and IIEP.

Evans, J. (2012). *Environmental Governance*. \[online\] Available at: <https://www.routledge.com/Environmental-Governance/Evans/p/book/9780415589826>

European Commission (2008). Communication from the Commission to the European Parliament, the Council, the European Economic and Social Committee and the Committee of the Regions Public procurement for a better environment {SEC(2008) 2124} {SEC(2008) 2125} {SEC(2008) 2126}

Falkner, R. (2003). Private Environmental Governance and International Relations: Exploring the Links. *Global Environmental Politics*, \[online\] 3(2), pp.72--87. doi:https://doi.org/10.1162/152638003322068227.

Farkova, A., Anchen, J., Ajit, V., Schmidt, A., Stolz, P., Wittbier, T. (2023). What goes around comes around: Insuring the circular economy. *Swiss Re Institute*.

‌Fisher-Kowalski, M., & Haberl, H. (2007). *Socioecological Transitions and Global Change*. \[online\] Available at: <https://www.e-elgar.com/shop/usd/socioecological-transitions-and-global-change-9781847203403.html> \[Accessed 2 Nov. 2023\].

Flachenecker, F., Bleischwitz, R. and Rentschler, J. (2018). The introduction and application of a comprehensive cost-benefit framework for resource efficiency investments. In F. Flachenecker and J. Rentschler, eds. *Investing in Resource Efficiency: The Economics and Politics of Financing the Resource Transition*. Heidelberg: Springer, pp. 87-104 

Georgescu-Roegen, N. (1971). *The Entropy Law and the Economic Process*. Cambridge, MA: Harvard University Press. <https://doi.org/10.4159/harvard.9780674281653>

Gerrard, S. (2000). The Early British Tin Industry. Tempus Publishing Ltd., Stroud, Gloucestershire, 176pp.

Goudie, A., Viles, A.H. (1997). *The Earth Transformed: An Introduction to the Human Impact on the Environment*. Wiley & Sons.

The Government Office for Science (2016). Report of the Government Chief Scientific Adviser 2016, From Waste to Resource Productivity: Evidence and case studies. *Government Office for Science*. Available online: <https://assets.publishing.service.gov.uk/media/5a82dd9740f0b62305b94c13/from-waste-to-resource-productivity-final-report.pdf> \[Accessed 27 Nov. 2023\]

Grubb, M. and Wieners, C. (2020). *Modeling Myths: On the Need for Dynamic Realism in DICE and other Equilibrium Models of Global Climate Mitigation*. \[online\] Social Science Research Network. Available at: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3536076> \[Accessed 2 Nov. 2023\].

Gunningham, N. (2009). Environment Law, Regulation and Governance: Shifting Architectures. *Journal of Environmental Law*, \[online\] 21(2), pp.179--212. Available at: <https://www.jstor.org/stable/44248690> \[Accessed 2 Nov. 2023\].

Gunningham, N., Grabosky, P. and Sinclair, D. (1999). *Smart Regulation: Designing Environmental Policy*. Oxford: Oxford University Press. 

Halme, M. and Laurila, J. (2008). Philanthropy, Integration or Innovation? Exploring the Financial and Societal Outcomes of Different Types of Corporate Responsibility. *Journal of Business Ethics*, 84(3), pp.325--339. doi:https://doi.org/10.1007/s10551-008-9712-5.

Hepburn, C. (2010). Environmental policy, government, and the market. *Oxford Review of Economic Policy*, 26(2), pp.117--136. doi:https://doi.org/10.1093/oxrep/grq016.

Hill, J. (2016). Circular Economy and the Policy Landscape in the UK. *Taking Stock of Industrial Ecology*, pp.265--274. doi:https://doi.org/10.1007/978-3-319-20571-7_13.

Hirsch, P. and Schempp, C. (2020). Categorisation System for the Circular Economy: A sector-agnostic approach for activities contributing to the circular economy. Directorate-General for Research and Innovation.

‌HM Government (2013). Prevention is better than cure: The role of waste prevention in moving to a more resource efficient economy. Available online: <https://assets.publishing.service.gov.uk/media/5a7c087640f0b645ba3c6479/pb14091-waste-prevention-20131211.pdf>

HM Government (2022). Resources and Waste Provisional Common Framework Framework Outline Agreement and Concordat. Available online:  <https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1125015/Resources_and_Waste_Provisional_Common_Framework_Command_Paper.pdf>

HM Government (2023). Mobilising Green Investment: 2023 Green Finance Strategy. Available online: <https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1149690/mobilising-green-investment-2023-green-finance-strategy.pdf>

HM Treasury (2018). Guide to developing the project business case better business cases: for better outcomes. Available online: <https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/749086/Project_Business_Case_2018.pdf>

HM Treasury (2023a). The Green Book (2022). Available online: <https://www.gov.uk/government/publications/the-green-book-appraisal-and-evaluation-in-central-governent/the-green-book-2020>

HM Treasury (2023b). HMT Public Spending Statistics. Available online: <https://www.gov.uk/government/collections/national-statistics-release>

Hodgson, G.M. (2018). Taxonomic definitions in social science, with firms, markets and institutions as case studies. *Journal of Institutional Economics*, 15(2), pp.207--233. doi:https://doi.org/10.1017/s1744137418000334.

Hoekstra, A.Y. and Wiedmann, T.O. (2014). Humanity's unsustainable environmental footprint. *Science*, 344(6188), pp.1114--1117.

Hood, C.C. (1983). *The Tools of Government*. London: Macmillan Education UK. doi:https://doi.org/10.1007/978-1-349-17169-9.

Hopkinson, P., Chen, H.-M., Zhou, K., Wang, Y. and Lam, D. (2019). Recovery and reuse of structural products from end-of-life buildings. *Proceedings of the Institution of Civil Engineers - Engineering Sustainability*, 172(3), pp.119--128. doi:https://doi.org/10.1680/jensu.18.00007.

Hopkinson, P., Cunningham, N., Brigg, J., Jain, M., Zils, M., Charnley, F. (Forthcoming) *Net Zero and Beyond: Why the Environment Agency should adopt a circular economy approach to flood risk management. CE-K-Hub*

Hopkinson, P., Zils, M., Charnley., Pencheon, D., Eatherly, D., Dawson,T., Burton, K., Gopfert, A. (2022) Accelerating the transition towards a net zero NHS https://ce-hub.org/knowledge-hub/accelerating-the-transition-towards-a-net-zero-nhs/

Hopkinson, P., and Zils, M. (unpublished, 2023a). Value creation. Week 2 reader from University of Exeter Circular Economy Masterclass. *University of Exeter*.

Hopkinson, P. and Zils, M. (unpublished, 2023b). Value capture. Week 3 reader from University of Exeter Circular Economy Masterclass. *University of Exeter*.

Hopkinson, P., and Zils, M. (unpublished, 2023c). Value leakage. Week 1 reader from University of Exeter Circular Economy Masterclass. *University of* Exeter.

Howlett, M. (2004). Beyond Good and Evil in Policy Implementation: Instrument Mixes, Implementation Styles, and Second Generation Theories of Policy Instrument Choice. *Policy and Society*, 23(2), pp.1--17. doi:https://doi.org/10.1016/s1449-4035(04)70030-2.

Hysing, E. (2009). Governing without government? The private governance of forest certification in Sweden. *Public Administration*, 87(2), pp.312--326. doi:https://doi.org/10.1111/j.1467-9299.2009.01750.x.

Iacovidou E., Ebner, N., Orsi, B. and Brown, A. (2020) Plastic packaging - How do we get to where we want to be? (Multidimensional Value Metrics for Assessing England's Plastic Packaging System and Monitoring Associated Targets - EV0301). Available at: <https://sciencesearch.defra.gov.uk/ProjectDetails?ProjectID=20471&FromSearch=Y&Publisher=1&SearchText=multidimensional%20value&SortString=ProjectCode&SortOrder=Asc&Paging=10> \[Accessed 27 Nov. 2023\]

Innovate UK. (2023). Circular critical materials supply chain programme: Private investment support. Available at: <https://iuk.ktn-uk.org/wp-content/uploads/2023/08/Circular-Critical-Minerals-Investment-Report_TW_D3.pdf> \[Accessed 28 Nov. 2023\]

Institute for Fiscal Studies (2023). Where does the government get its money? Available online: <https://ifs.org.uk/taxlab/taxlab-key-questions/where-does-government-get-its-money> \[Accessed 27 Nov. 2023\]

IPCC (2022). Mitigation of Climate Change Climate Change 2022 Working Group III contribution to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change, https://www.ipcc.ch/site/assets/uploads/2018/05/uncertainty-guidance-note.pdf.

IRP (2020). Resource Efficiency and Climate Change: Material Efficiency Strategies for a Low-Carbon Future. Hertwich, E., Lifset, R., Pauliuk, S., Heeren, N. A report of the International Resource Panel. United Nations Environment Programme. Nairobi: Kenya.

IRP (2021). Global Material Flows Database. Available at: <https://www.resourcepanel.org/global-material-flows-database> \[Accessed 3 Nov. 2023\]

Jaeger, B. and Upadhyay, A. (2020). "Understanding barriers to circular economy: cases from the manufacturing industry", *Journal of Enterprise Information Management*, Vol. 33 No. 4, pp. 729-745. <https://doi.org/10.1108/JEIM-02-2019-0047>

Jevons, W.S. (1866). *The coal question ; an inquiry concerning the progress of the nation, and the probable exhaustion of our coal-mines.* London: Macmillan And Co.

Jones, G. and Rowley-Conwy, P. (2007). On the importance of cereal cultivation in the British Neolithic. In: Colledge, S., Conolly, J. (Eds.), *The Origins and Spread of Domestic Plants in Southwest Asia and Europe*. Walnut Creek: Left Coast Press. pp. 391--419

‌Keep Britain Tidy (2020). Litter composition analysis: summary report. Available at: <https://www.keepbritaintidy.org/sites/default/files/resources/20200330%20KBT%20Litter%20Composition%20Report%20-%20FINAL.pdf> \[Accessed 2 Nov. 2023\]

Keirsbilck, B., Terryn, E., Algona, M.I. (2020). Sustainable Consumption and Consumer Protection Legislation How can sustainable consumption and longer lifetime of products be promoted through consumer protection legislation? Policy Department for Economic, Scientific and Quality of Life Policies Directorate-General for Internal Policies. Available at: <https://www.europarl.europa.eu/RegData/etudes/IDAN/2020/648769/IPOL_IDA(2020)648769_EN.pdf>.

Kirchherr, J., Reike, D. and Hekkert, M. (2017). Conceptualizing the circular economy: an analysis of 114 definitions. *Resources, Conservation and Recycling*, 127(0921-3449), pp.221--232.

Kivimaa, P. and Kern, F. (2016). Creative destruction or mere niche support? Innovation policy mixes for sustainability transitions. *Research Policy*, 45(1), pp.205--217. doi:https://doi.org/10.1016/j.respol.2015.09.008.

Klooster, D. (2005). Environmental certification of forests: The evolution of environmental governance in a commodity network. *Journal of Rural Studies*, 21(4), pp.403--417. doi:https://doi.org/10.1016/j.jrurstud.2005.08.005.

Kooiman, J. (1993). *Modern Governance.* Sage.

Kooiman, J. (2003). Societal Governance. *Demokratien in Europa*, pp.229--250. doi:https://doi.org/10.1007/978-3-663-09584-2_11.

Krausmann, F., Weisz, H., & Eisenmenger, N. (2016). Transitions in Sociometabolic Regimes: Throughout Human History. *Springer eBooks*, pp.63--92. doi:https://doi.org/10.1007/978-3-319-33326-7_3.

Lee, B., Preston, F., Kooroshy, J., Bailey, R. and Lahn, G. (2012). *Executive Summary and Recommendations Resources Futures*. Available at: <https://www.chathamhouse.org/sites/default/files/field/field_document/Executive%20Summary%20Resources%20Futures.pdf> \[Accessed 2 Nov. 2023\]

Lee, P., Walsh, B., Smith, P. (2007). Quantification of the business benefits of resource efficiency: A research report completed for the Department for Environment, Food and Rural Affairs. Available at: <https://www.oakdenehollins.com/reports/2007/10/1/quantification-of-the-business-benefits-of-resource-efficiency> \[Accessed 2 Nov. 2023\]

Lee, P., Bell, N., Bertham, O. (2017). Business Resource Efficiency Quantification of the no cost/low cost resource efficiency opportunities in the UK economy in 2014 (Project ID EV0482).

Lieder, M. and Rashid, A. (2016). Towards circular economy implementation: a comprehensive review in context of manufacturing industry. *Journal of Cleaner Production*, 115(115), pp.36--51. doi:https://doi.org/10.1016/j.jclepro.2015.12.042.

London School of Economics. (2023). What is the blue economy? *Grantham Research Institute on Climate Change and the Environment*. Available online: <https://www.lse.ac.uk/granthaminstitute/explainers/what-is-the-role-of-the-blue-economy-in-a-sustainable-future/#:~:text=The%20blue%20economy%2C%20or%20the,livelihoods%20and%20ocean%20ecosystem%20health> \[Accessed 28 Nov. 2023\]

Lorenzoni, I. and Benson, D. (2014). Radical institutional change in environmental governance: Explaining the origins of the UK Climate Change Act 2008 through discursive and streams perspectives. *Global Environmental Change*, 29, pp.10--21. doi:https://doi.org/10.1016/j.gloenvcha.2014.07.011.

Lysaght, O., Khedmati-Morasae, E., Zils, M., and Hopkinson, P. (2022). A guide to public data resources for a circular economy modelling & measurement framework. CE-Hub Technical Report. CE-Hub Technical Report. Available at: <https://ce-hub.org/knowledge-hub/ce-hub-technical-report-a-guide-to-public-data-resources-for-a-circular-economy-modelling-and-measurement-framework/> \[Accessed 27 Nov. 2023\]

Maddison, A. (2008). Historical Statistics of the World Economy: 1-2008 AD. Available at: <https://web.archive.org/web/20211102093357/http%3A%2F%2Fwww.ggdc.net%2Fmaddison%2Foriindex.htm> \[Accessed 2 Nov. 2023\]

Mähönen, J.T. (2019). Financing sustainable market actors in circular economy. in E Eftestøl-Wilhelmsson, S Sankari & A Bask (eds), *Sustainable and Efficient Transport: Incentives for Promoting a Green Transport Market.* Edward Elgar, pp. 95-116. https://doi.org/10.4337/9781788119283.00016

Maitre-Ekern, E. and Dalhammar, C. (2019). Towards a hierarchy of consumption behaviour in the circular economy. *Maastricht Journal of European and Comparative Law*, 26(3), pp.394--420. doi:https://doi.org/10.1177/1023263x19840943.

Marshall., R., Velenturf, A., Jopson, J. (2018). *Making the Most of Industrial Wastes: Strengthening Resource Security of Valuable Metals for Clean Growth in the UK*; Policy and Practice Note; Resource Recovery from Waste: Leeds, UK.

Maskell, P. (2000). Social Capital, Innovation, and Competitiveness. in S Baron, J Field & T Schuller (eds), *Social Capital: Critical Perspectives.* Oxford University Press, Oxford, pp. 111-123. Available at: <https://research.cbs.dk/en/publications/social-capital-innovation-and-competitiveness> \[Accessed 3 Nov. 2023\]

Mazzucato, M. (2013). The Entrepreneurial State: Debunking public vs. private sector myths. London: Anthem Press.

McCarthy, A., R. Dellink and R. Bibas (2018). "The Macroeconomics of the Circular Economy Transition: A Critical Review of Modelling Approaches", *OECD Environment Working Papers*, No. 130, OECD Publishing, Paris, https://doi.org/10.1787/af983f9a-en.

Melati, K., Nikam, J., and Nguyen, P. (2021). Barriers and drivers for enterprises to transition to circular economy. *SEI brief*. http://doi.org/10.51414/sei2021.029.

Milios, L. (2021). Towards a Circular Economy Taxation Framework: Expectations and Challenges of Implementation. *Circular Economy and Sustainability*, 1. doi:https://doi.org/10.1007/s43615-020-00002-z.

Nachtigall, D., et al. (2022). "The climate actions and policies measurement framework: A structured and harmonised climate policy database to monitor countries' mitigation action", *OECD Environment Working Papers*, No. 203, OECD Publishing, Paris, <https://doi.org/10.1787/2caa60ce-en>.

‌National Audit Office (2014). Using alternatives to regulation to achieve policy objectives. Available at: <https://www.nao.org.uk/wp-content/uploads/2014/06/Using-alternatives-to-regulation-to-achieve-policy-objectives1.pdf>

Nemet, G.F. (2009). Demand-pull, technology-push, and government-led incentives for non-incremental technical change. *Research Policy*, 38(5), pp.700--709. doi:https://doi.org/10.1016/j.respol.2009.01.004.

Newell, P. (2008). The Political Economy of Global Environmental Governance. *Review of International Studies*, *34*(3), 507--529.

Nolan, R., Lysaght, O., and Hopkinson, P. (2022) Circular data for the circular economy. *CE Hub*. Available at: <https://ce-hub.org/knowledge-hub/ce-hub-technical-report-a-guide-to-public-data-resources-for-a-circular-economy-modelling-and-measurement-framework/> \[Accessed 28 Nov. 2023\]

Nolan, R. (2023). Why public data is a vital part of the UK's transition to a circular economy. *Exeter Expertise*. Available at: <https://business-school-expertise.exeter.ac.uk/article/public-data-transition-circular-economy/> \[Accessed 28 Nov. 2023\]

Office for Budgetary Responsibility (2021). Fiscal risks report 2021. Available at: <https://obr.uk/fiscal-risks-report-2021-2/> \[Accessed 3 Nov. 2023\]

Office for Budgetary Responsibility (2022). Economic and fiscal outlook - March 2022, Box: 2.5, p. 55. Available at: <https://obr.uk/publications/economic-and-fiscal-outlook-march-2022/> \[Accessed 3 Nov. 2023\]

OECD (2000). *Voluntary Approaches for Environmental Policy: An Assessment*, OECD Publishing, Paris, <https://doi.org/10.1787/9789264180260-en>.

OECD (2001). *Extended Producer Responsibility: A Guidance Manual for Governments*, OECD Publishing, Paris, <https://doi.org/10.1787/9789264189867-en>.

OECD (2003). *Voluntary Approaches for Environmental Policy: Effectiveness, Efficiency and Usage in Policy Mixes*, OECD Publishing, Paris, <https://doi.org/10.1787/9789264101784-en>.

OECD (2007). Instrument Mixes for Environmental Policy. OECD Publishing, Paris, <https://doi.org/10.1787/9789264018419-en>.

OECD (2018), *Cost-Benefit Analysis and the Environment: Further Developments and Policy Use*, OECD Publishing, Paris, <https://doi.org/10.1787/9789264085169-en>.

OECD (2019). *Global Material Resources Outlook to 2060: Economic Drivers and Environmental Consequences*, OECD Publishing, Paris, [doi.org/10.1787/9789264307452-en](https://doi.org/10.1787/9789264307452-en).

OECD (2020a). The Circular Economy in Cities and Regions: Synthesis Report. <https://doi.org/10.1787/10ac6ae4-en>

OECD (2020b). "Improving resource efficiency and the circularity of economies for a greener world", *OECD Environment Policy Papers*, No. 20, OECD Publishing, Paris, <https://doi.org/10.1787/1b38a38f-en>.

OECD (2021a). Recommendation of the Council for Agile Regulatory Governance to Harness Innovation. Available at: <https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0464>

OECD (2021b). Towards a more resource-efficient and circular economy: the role of the G20. Available at: <https://www.oecd.org/environment/waste/OECD-G20-Towards-a-more-Resource-Efficient-and-Circular-Economy.pdf>

OECD (2022). [OECD Environmental Performance Reviews: United Kingdom 2022](https://doi.org/10.1787/b6a2be87-en "Click for more details about this publication on oecd-iLibrary.org"). Available at: <https://www.oecd-ilibrary.org/sites/edf6758d-en/index.html?itemId=/content/component/edf6758d-en#section-d1e10091>

Office for Health Improvement and Disparities (2018). Creating a logic model for an intervention: evaluation in health and wellbeing.

Office for National Statistics (2019). Taxes and fees for sales of service: how they differ and why it is important. Available at: <https://www.ons.gov.uk/economy/governmentpublicsectorandtaxes/publicsectorfinance/articles/taxesandfeesforsalesofservicehowtheydifferandwhyitisimportant/2019-05-31>\[Accessed 3 Nov. 2023\]

Office for National Statistics (2023a). Material flow accounts: 2023. Available at: <https://www.ons.gov.uk/economy/environmentalaccounts/datasets/ukenvironmentalaccountsmaterialflowsaccountunitedkingdom> \[Accessed 3 Nov. 2023\]

Office for National Statistics (2023b). Material footprint in the UK. Available at: <https://www.ons.gov.uk/economy/environmentalaccounts/datasets/materialfootprintintheuk> \[Accessed 3 Nov. 2023\]

Office for National Statistics (2023c). Environmental goods and services sector (EGSS) estimates. Available at: <https://www.ons.gov.uk/economy/environmentalaccounts/datasets/ukenvironmentalgoodsandservicessectoregssestimates> \[Accessed 3 Nov. 2023\]

Office for National Statistics (2023d) UK manufacturers' sales by product. Available at: <https://www.ons.gov.uk/businessindustryandtrade/manufacturingandproductionindustry/datasets/ukmanufacturerssalesbyproductprodcom> \[Accessed 28 Nov. 2023\]

Olander, F. and Thøgersen, J. (2014). *Informing versus Nudging in Environmental Policy*. \[online\] Social Science Research Network. Available at: <https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2597494> \[Accessed 7 Nov. 2023\].

O'Neill, D.W., Fanning, A.L., Lamb, W.F. and Steinberger, J.K. (2018). A good life for all within planetary boundaries. *Nature Sustainability*, \[online\] 1(2), pp.88--95. doi:https://doi.org/10.1038/s41893-018-0021-4.

Page MJ, McKenzie JE, Bossuyt PM, Boutron I, Hoffmann TC, Mulrow CD, et al. The PRISMA 2020 statement: an updated guideline for reporting systematic reviews. BMJ 2021;372:n71. doi: 10.1136/bmj.n71

Pearce, D. (2001). Measuring resource productivity, Paper to DTI/Green Alliance Conference, February 2001, London.

Pigou, A. (1920). *The Economics of Welfare*. Macmillan.

Porter, M.E. and van der Linde, C. (1995). Toward a New Conception of the Environment-Competitiveness Relationship. *The Journal of Economic Perspectives*, \[online\] 9(4), pp.97--118. Available at: <https://www.jstor.org/stable/2138392>.

‌Rezaie, S., Vanhuyse, F., André, K., Henrysson, M. (2022). *Governing the circular economy: how urban policymakers can accelerate the agenda.* Stockholm Environment Institute. https://doi.org/10.51414/sei2022.027

Richardson, K., Steffen, W., Lucht, W., Bendtsen, J., Cornell, S., Donges, J.F., Drüke, M., Fetzer, I., Bala, G., Werner von Bloh, Feulner, G., Fiedler, S., Gerten, D., Gleeson, T., Hofmann, M., Willem Huiskamp, Matti Kummu, Mohan, C., Bravo, D. and Petri, S. (2023). Earth beyond six of nine planetary boundaries. *Science Advances*, 9(37). doi:https://doi.org/10.1126/sciadv.adh2458.

RPC (2019). RPC Small and Micro Business Assessment (SaMBA) guidance. Available at:<https://www.gov.uk/government/publications/small-and-micro-business-assessment-samba-guidance> \[Accessed 3 Nov. 2023\]

Ruddiman, W.F. (2003). The Anthropogenic Greenhouse Era Began Thousands of Years Ago. *Climatic Change*, 61(3), pp.261--293. doi:https://doi.org/10.1023/b:clim.0000004577.17928.fa.

Sandén, B.A. and Azar, C. (2005). Near-term technology policies for long-term climate targets---economy wide versus technology specific approaches. *Energy Policy*, 33(12), pp.1557--1576. doi:https://doi.org/10.1016/j.enpol.2004.01.012.

‌Santana, R. (2023). Greening the HS: What are the limits and the alternatives? Joint OECD/UNECE Seminar on Implementation of SEEA.

Scharpf, F.W. (1997). *Games Real Actors Play: Actor-centered Institutionalism In Policy Research.* Westview Press.

Schröder, P., Raes, J. (2021). Financing an inclusive circular economy. Available at: <https://www.chathamhouse.org/2021/07/financing-inclusive-circular-economy>

Sharpe, S., Mercure, J-F., Vinuales, J., Ives, M., Grubb, M., Pollitt, H., Knobloch, F. and Nijsse, F.J.M.M. (2021). Deciding how to decide: Risk-opportunity analysis as a generalisation of cost-benefit analysis. UCL Institute for Innovation and Public Purpose, Working Paper Series (IIPP WP 2021/03). Available at: <https://www.ucl.ac.uk/bartlett/public-purpose/wp2021-03>   

Smil, V. (2022). *How the World Really Works.* Viking.

Smith, K.B. (2002). Typologies, Taxonomies, and the Benefits of Policy Classification. *Policy Studies Journal*, 30(3), pp.379--395. doi:https://doi.org/10.1111/j.1541-0072.2002.tb02153.x.

Sørensen, E. and Torfing, J. (2007). *Theories of Democratic Network Governance*. London: Palgrave Macmillan UK. doi:https://doi.org/10.1057/9780230625006.

Sterner, T. and Coria, J. (2013). Policy Instruments for Environmental and Natural Resource Management. *Policy Instruments for Environmental and Natural Resource Management, Second Edition*. 1-638. 10.4324/9781315780894.

‌Steurer, R. (2013). Disentangling governance: a synoptic view of regulation by government, business and civil society. *Policy Sciences*, \[online\] 46(4), pp.387--410. doi:https://doi.org/10.1007/s11077-013-9177-y.

Storper, M. (1997). The regional world: Territorial development in a global economy. New York: Guilford Press.

Syla-Beqiri, F. (2020). *The Strategic Role of Circular Procurement*. \[online\] CSCP gGmbH. Available at: <https://www.cscp.org/circular-procurement/> \[Accessed 2 Nov. 2023\].

Thomas, R. and Dimsdale, N (2017). "A Millennium of UK Data", Bank of England OBRA dataset. Available at: <http://www.bankofengland.co.uk/research/Pages/onebank/threecenturies.aspx>

‌Tiippana-Usvasalo, M., Pajunen, N., and Maria, H. (2023). The role of education in promoting circular economy. *International Journal of Sustainable Engineering*, 16:1, 92-103, DOI: 10.1080/19397038.2023.2210592

UNCTAD (2019). International Classification of Non-tariff Measures - 2019 version. Available at: <https://unctad.org/system/files/official-document/ditctab2019d5_en.pdf>.

UNCTAD (2023). Key statistics and trends in trade policy 2022: Green goods trade and trade policies. Available at: <https://unctad.org/system/files/official-document/ditctab2023d2_en.pdf>.

UNECE (2021). Enhancing the Transparency and Traceability of Sustainable Value Chains in the Garment and Footwear Sector. <https://unece.org/sites/default/files/2021-05/Ecosystem_report-April2021.pdf>

UNEP (2011). Decoupling natural resource use and environmental impacts from economic growth. A Report of the Working Group on Decoupling to the International Resource Panel. Fischer-Kowalski, M., Swilling, M., von Weizsäcker, E.U., Ren, Y., Moriguchi, Y., Crane, W., Krausmann, F., Eisenmenger, N., Giljum, S., Hennicke, P., Romero Lankao, P., Siriban Manalang, A. United Nations Environment Programme

UNEP (2019). Global Resources Outlook 2019: Natural Resources for the Future We Want. A Report of the International Resource Panel. United Nations Environment Programme. Nairobi, Kenya.

UN PRI (2022). Responsible Investment and the Circular Economy. <https://www.unpri.org/sustainability-issues/environmental-social-and-governance-issues/environmental-issues/circular-economy>

UN PRI (2022). Closing the loop: Responsible investment and the circular economy. Available at: <https://www.unpri.org/download?ac=17130>

Upadhyay, A., Kumar, A. and Akter, S. (2021). An analysis of UK retailers' initiatives towards circular economy transition and policy-driven directions. *Clean Technologies and Environmental Policy*. \[online\] doi:https://doi.org/10.1007/s10098-020-02004-9.

US Census Bureau (2022) Historical Estimates of World Population. Available at: \[online\] https://www.census.gov/data/tables/time-series/demo/international-programs/historical-est-worldpop.html

van Ewijk, S. (2018). *Resource efficiency and the circular economy Concepts, economic benefits, barriers, and policies*. \[online\] Available at: <https://discovery.ucl.ac.uk/id/eprint/10054117/1/14264_Resourceefficiencyandcirculareconomy.pdf>.

van Rossem, C., Tojo, N., Lindhqvist, T. (2006). *Extended Producer Responsibility An examination of its impact on innovation and greening products.* Available at: <https://friendsoftheearth.eu/wp-content/uploads/2012/06/extended_producer_responsibility.pdf>.

Weber, K.M. and Rohracher, H. (2012). Legitimizing research, technology and innovation policies for transformative change. *Research Policy*, 41(6), pp.1037--1047. doi:https://doi.org/10.1016/j.respol.2011.10.015.

Wentworth, J. and Burgon, J. (2016). Designing a Circular Economy. Post Note Number 536.

West, R. and Michie, S. (2020). A brief introduction to the COM-B Model of behaviour and the PRIME Theory of motivation \[v1\]. *Qeios*. \[online\] Available at: <https://discovery.ucl.ac.uk/id/eprint/10095640/>.

Whitefoot, K.S. and Skerlos, S.J. (2012). Design incentives to increase vehicle size created from the U.S. footprint-based fuel economy standards. *Energy Policy*, 41, pp.402--411. doi:https://doi.org/10.1016/j.enpol.2011.10.062.

Wijkman, A. (2021). Reflections on Governance for a Circular Economy. Available at: <https://globalchallenges.org/library/reflections-on-governance-for-a-circular-economy-2021/>

Wilkinson, M., Dumontier, M., Aalbersberg, I. et al. (2016). The FAIR Guiding Principles for scientific data management and stewardship. *Sci Data* 3, 160018. https://doi.org/10.1038/sdata.2016.18

Wilts, H. and O'Brien, M. (2019). A Policy Mix for Resource Efficiency in the EU: Key Instruments, Challenges and Research Needs. *Ecological Economics*, 155, pp.59--69. doi:https://doi.org/10.1016/j.ecolecon.2018.05.004.

World Economic Forum (2019). The Next Frontier: Natural Resource Targets Shaping a Competitive Circular Economy within Planetary Boundaries. Available at: <https://www3.weforum.org/docs/WEF_The_Next_Frontier_Natural_Resource_Targets_Report.pdf>.

World Economic Forum (2022). The Global Risks Report 2022 17th Edition. Available at: <https://www3.weforum.org/docs/WEF_The_Global_Risks_Report_2022.pdf>

World Bank (2022). Squaring the Circle: Policies from Europe's Circular Economy Transition. Available at: <https://documents1.worldbank.org/curated/en/099425006222229520/pdf/P174596025fa8105a091c50fb22f0596fd1.pdf>

World Bank (2023). United Kingdom. Available at: <https://data.worldbank.org/country/GB>

WRAP (2019). Textiles Market Situation report 2019. Available at: <https://wrap.org.uk/resources/market-situation-reports/textiles-2019>

WRAP (2022). Food surplus and waste in the UK -- key facts. Available at: <https://wrap.org.uk/sites/default/files/2023-01/Food%20Surplus%20and%20Waste%20in%20the%20UK%20Key%20Facts%20December%202022.pdf> \[Accessed 27 Nov. 2023\]

WRAP (2023). Textiles Policy Options and Cost Benefit Analysis. https://wrap.org.uk/resources/report/textiles-policy-options-and-cost-benefit-analysis

Yamaguchi, S. (2021). International Trade and Circular Economy - Policy Alignment. *OECD Trade and Environment Working Papers*. \[online\] doi:https://doi.org/10.1787/ae4a2176-en.

Zils, M., Hopkinson, P., Khedmati Morasae, E., Nolan, R., Charnley, F., Lysaght, O., Abu-Bakar, H., & Reynolds, M. (2023). Measuring Circular Economy implementation and performance through KPIs. UKRI Circular Economy Hub, working paper series (CE-Hub WP 2023-1). Available at: https://ce-hub.org/knowledge-hub/measuring-circular-economy/  \[Accessed 3 Dec. 2023\]

Zils, M., Howard, M., and Hopkinson, P. (2023). Circular economy implementation in operations & supply chain management: Building a pathway to business transformation. *Production Planning and Control*, DOI: 10.1080/09537287.2023.2280907.

Zils, M., and Hopkinson, P. (unpublished, 2023). Optimising the value chain. Week 4 reader from University of Exeter Circular Economy Masterclass. *University of Exeter*
