---
title: "{{< fa arrow-up >}} Direction-setting"
---

# Summary

::: {.callout-note collapse="false" appearance="simple" icon="false"}
Organisational capacities are a key resource of the state in resolving transition failures (Duit, 2016). Designing and introducing the right strategies and targets which effectively drive society towards sought outcomes in the circular economy are important.

In the 25 Year Environment Plan, the UK Government committed to improving the environment within a generation. Reducing the pressures that our consumption of natural capital and production of wastes places on the environment is a crucial part of doing so. Globally, attention is increasingly turning towards the importance of targets related to resource use (WEF, 2020) and in several key government strategies, the Government has publicly committed to at least doubling national resource productivity by 2050: the Industrial Strategy, the 25 Year Environment Plan, and most recently, the Resources and Waste Strategy. Increasing resource productivity was further identified as a priority in the Clean Growth Strategy.
:::

# How it works and current applications

::: {.callout-note collapse="true" appearance="simple" icon="false"}
## Plans and strategies

-   Scotland - [Making Things Last](https://www.gov.scot/binaries/content/documents/govscot/publications/strategy-plan/2016/02/making-things-last-circular-economy-strategy-scotland/documents/00494471-pdf/00494471-pdf/govscot%3Adocument/00494471.pdf) (2016)

-   Wales - [Beyond Recycling](https://gov.wales/sites/default/files/publications/2021-03/beyond-recycling-strategy-document.pdf) (2021) - The 2021 Beyond Recycling Strategy sets out the ambition of the Welsh Government to one planet resource use by 2050, whereby Wales will use its fair share of resources.

-   The Waste Management Plan for Northern Ireland emphasises the role of resource efficiency in delivering resource management objectives. [Circular Economy Strategy for Northern Ireland](https://www.economy-ni.gov.uk/consultations/circular-economy-strategy-northern-ireland#:~:text=The%20draft%20Circular%20Economy%20Strategy%20for%20Northern%20Ireland%20is%20a,across%20government%2C%20business%20and%20society.)

-   A UK-level Sustainable Consumption and Production (SCP) framework called 'Changing Patterns' was established in 2003 (Defra, 2003), with a general action plan for its implementation proposed in chapter 3 of the 2005 UK Sustainable Development Strategy (Defra, 2005). The 2005 strategy called for improvement in three major areas in order to decouple resource utilisation from economic growth and detoxify the environment: 1) "Better products and services, which reduce the environmental impacts from the use of energy, resources, or hazardous substances; 2) Cleaner, more efficient production processes (doing more with less), which strengthen competitiveness; and 3) Shifts in consumption towards goods and services with lower impacts" (DEFRA, 2005: 44).

-   The 2008 Waste Framework Directive (2008/98/EC) also required all member states to produce Waste Prevention Programmes by the end of 2013 (EC [2008](https://link.springer.com/chapter/10.1007/978-3-319-20571-7_13#ref-CR4 "EC. (2008). Directive 2008/98/EC of the European Parliament and of the Council of 19th November 2008 on waste and repealing certain directives. E. Commission. Brussels: European Commission.")) to deliver preventive and integrated approaches to tackling waste efficienctly. These were developed by each of the UK's constituent countries.
:::

::: {.callout-tip collapse="true" appearance="simple" icon="false"}
## Targets

In categorising targets for sustainable materials management, Petersen et al. (2010) distinguish between mandatory hard targets characterised by short timelines, typically narrow scope, clear accountability and quantifiability, soft targets characterised by longer timelines, being broader in scope and associated with a level of flexibility in accountability and voluntary targets which are similar to soft targets but are entered into voluntarily.

Targets are cross-cutting e.g. EPR for WEEE and packaging partly based on target-setting.

Dutch Economy aims to be 100% circular by 2050
:::

# Performance

## Strategic fit

## Effectiveness and efficiency

### Effectiveness

The effectiveness of instruments providing strategic direction on the circular economy have been found to vary. A [2023 review](https://circulareconomy.europa.eu/platform/sites/default/files/2023-07/Court%20of%20Auditors%20CE%20Report_SR-2023-17_EN.pdf) by the The European Court of Auditors found that 'Overall there is limited evidence that the Commission's Circular Economy Action Plans (CEAPs), and in particular the actions regarding the circular design of products and of production processes, were effective in influencing circular-economy activities in the member states.'

The 2012 [Resource Security Action Plan](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/69511/pb13719-resource-security-action-plan.pdf) led by Defra and BIS focussed on metals and minerals perceived to be of particular strategic importance but with uncertain supply. As part of the plan, strategies focussed on improved resource efficiency and increased secondary material use were viewed as promising ways to tackle potential scarcities. The plan emphasised recovery moreso than opening up new sources of materials (Hill, 2016). Critical Minerals Strategy.

Following the 2017 Chief Scientific Advisors Office's report 'From Waste to Resource Productivity' which called for the development of a national strategy to deliver this transition, the [Resources and Waste Strategy](https://www.gov.uk/government/publications/resources-and-waste-strategy-for-england) (RWS) for England published in 2018 by Defra sets out a strategic ambition to double resource productivity and eliminate avoidable waste of all kinds by 2050 in line with the direction of the 25 Year Environment Plan. A [2023 National Audit Office review](https://www.nao.org.uk/reports/government-resources-and-waste-reforms/) found [Progress review](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1130074/E02830979_Un-Act_Monitoring_Progress_with_the_EOP_Web_Accessible_V2.pdf) on 25YEP by the OEP

A [2021 assessment](https://wrap.org.uk/resources/report/review-waste-prevention-programme-england-2013-summary-report) of England's [first Waste Prevention Programme](https://www.gov.uk/government/publications/waste-prevention-programme-forengland) undertaken by Wrap with support from Defra found... . No quantitative targets as part of the WPP but some initiatives within the programme do have their own targets aimed specifically at different materials/sectors, such as the Courtauld Agreement. A consultation for an updated Waste Prevention Programme released in 2021 expanded particularly on interventions to be taken to move waste treated up the hierarchy. After the UK's EU Exit, the Environment Bill was introduced to provide the required primary legislation framework for realising many of the policy aims of the RWS.

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Read more

+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| **Country** | **Objective**                                                                                                                                                                                                    | **Method**                                                             |
+=============+==================================================================================================================================================================================================================+========================================================================+
| Austria     | 50% increase in resource efficiency 2008-20 (Austrian Resource Efficiency Action Plan). Aspires to 4-10 fold improvement by 2050                                                                                 | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Estonia     | 10% increase in resource efficiency 2015-19 (Coalition Agreement)                                                                                                                                                | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| France      | 30% increase in resource productivity 2010-30 and decrease in per-person DMC in this period (Energy Transition for Green Growth Act)                                                                             | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Germany     | Double abiotic material productivity 1994-2020 (2002 National Sustainable Development Strategy) -- expected that only 65% of target will be reached by 2020                                                      | GDP/DMI~abiotic~ (excludes biotic materials but includes fossil fuels) |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Germany     | Increase total raw material productivity by an average of 1.5% per year between 2010-30 (Progress II) -- as a complement to 2002 target                                                                          | Numerator: GDP & sum of monetary value of imports                      |
|             |                                                                                                                                                                                                                  |                                                                        |
|             |                                                                                                                                                                                                                  | Denominator: Raw Material Input                                        |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Hungary     | Reduce material intensity to 80% of 2007 levels by 2020 (Hungarian National Reform Programme)                                                                                                                    | DMC/GDP                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Japan       | Increase resource productivity 40% by 2010 compared to 2000 (to 370,000 YEN/tonne) and 60% by 2015 compared to 2000 (420,000 YEN/tonne) or 770000 YEN/tonne when excluding the input of earth and rock resources | GDP/DMI                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Latvia      | Increase resource productivity to EUR 710/tonne in 2030, with intermediate targets of EUR 540/tonne and EUR 600/tonne in 2020                                                                                    | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Poland      | Increase resource productivity to EUR 0.45/kg by 2015 and EUR 0.5/kg by 2020 (Strategy for Innovation and Efficiency of the Economy)                                                                             | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Portugal    | Increase resource productivity from EUR 1.14/kg in 2013 to EUR 1.17/kg in 2020 and EUR 1.72/kg in 2030 (Green Growth Commitment)                                                                                 | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+
| Slovenia    | Increase resource productivity from EUR 1.07/kg in 2011 to EUR 1.5/kg in 2020                                                                                                                                    | GDP/DMC                                                                |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------+

: \
Austria aims to achieve a four- to ten-fold increase in resource productivity above 2008 levels by 2050. Germany, in its revised ProgRess II strategy, adopted a target to maintain until 2030 an average annual increase of 1.5% in total raw material productivity, defined as (GDP+ monetary value of imports)/raw material input. More recently, the Dutch Government Programme for a Circular Economy included an (interim) objective of a 50% reduction in the use of primary raw materials (minerals, fossil materials and metals) compared with 2014 by the year 2030.
:::

### Cost-effectiveness and efficiency

## Affordability and feasibility

## Long-run effects

## Distributional effects

## Positive and negative spillovers

# Conditions for effectiveness

## Design and implementation considerations

Beyond the general prescription that current levels of primary material use in industrialised countries is likely higher that what might be sustainable (Bleischwitz, ), quantifying more precisely what a 'sustainable' level of resource use might look like, has proven difficult. Indeed, the very definition of sustainability is not without contention. The World Commission on Environment and Development (WCED) in 1987 defined sustainable development as *'development that meets the needs of the present without compromising the ability of future generations to meet their own'*. The capital framing of sustainable development interprets this as an injunction to preserve productive capacity for the indefinite future (Solow, 1993), so as to provide future generations with the opportunity to be as well off as those present.

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Read more

Productive capacity is generally defined under this framing as a portfolio of capital assets e.g. built, human, social, financial and natural capital. While the constructed perspective of nature as an asset to be managed within a capital accounting framework may improve on more nebulous concepts of sustainability as a basis for measuring progress towards that aim (Barbier, 2010), natural capital differs from other types of capital assets on at least three important counts: 1) depreciation of NC is often irreversible once certain thresholds are passed, with limited opportunities for effective restoration (Benayas et al. 2013); 2) except in a limited sense, it isn't possible to replace a depleted ecosystem with a new one, or even its components (Fritter, 2013); and 3) ecosystems can collapse abruptly (Dasgupta, 2008). Not only this, but natural capital remains the fundamental building block for all other forms of man-made capital and economic activity and underpins the survival of humans and other animals.

Hicks (1946) defined sustainable use as *'the maximum amount that a community can consume over a given time period and still be as well off at the end of the period as at the beginning'*. By 'well off', Hicks implied having the same capacity to produce income in a future year as in a year past, premised on maintaining a constant stock of capital capable of yielding goods and services valued by people. There exists significant debate as to the necessary composition of the portfolio of capital assets each generation should hand down to ensure futurity have the same opportunities for welfare as current generations have. In the presence of ecological thresholds, discontinuities, interlinkages, non-linearities, non-convexities and possible regime shifts driven by the likes of climate change, as well as some level of concern for non-human species, the optimal path of consumption of, and investment in, natural capital derived within a dynamic welfare maximizing framework is likely to mimic as close to a strong sustainability rule as possible i.e. the value of our natural capital should be maintained, if not enhanced (Irwin, Gopalakrishnan and Randall, 2016), with this particularly the case for industrialized nations that are often relatively ecologically denuded (Helm, ). While it might be seen that in an 'empty world' where levels of human-made capital was a limiting factor to development and natural capital is superabundant, substitution of natural for human capital was likely to bring additional human welfare benefits, in a 'fuller world' (particularly for industrialized countries) associated with greater quantities of human capital but relatively less natural capital, this limit has increasingly become a limiting factor (Daly, 1995).

Overuse might be written as E\>A (where r is emissions of residuals and a is the assimilative/regenerative/absorptive capacity of the receiving environment). Overuse will depend on the nature of the pollutant e.g. CO2 as a stock pollutant residuals in the atmosphere for \~60 years, makinf assimilative capacity lower across a human lifetime and therefore optimal pollution rate per annum lower too). Given sink functions are amost always unpriced, over-use is almost always the likely outcome, necessitating governance and policy oversight.

In light of recognition of the non-substitutability between diferent types of natural capital, SS proponents e.g. Costanza and Daly (1992) have dropped aggregate natural capital rule and argue instead that minimum stocks of all natural resources should be maintained (Faucheux and O'Connor, 1995).

Though overuse might be resource-specific, it can also be linked to other resource limits through ecosystems due to their interconnectedness, that is, use/renewal rates cannot always be dealt with in isolation due to ecological contingencies.

The snowballing number of nations introducing targets at a national level on greenhouse gas emissions as coordinated under the UNFCCC (firstly the prescriptive and market-based of the Kyoto Protocol and more recently the self-declarative INDCs under the Paris Accord), alongside co-regulation by the private sector, the public and charities, is focussed on tackling one of the most serious impacts on the environment by human societies -- greenhouse gas emissions. It is becoming increasingly recognised that environmental impacts cannot be effectively mitigated by focussing on emissions abatement alone, however (Bringezu et al. 2017).

Beyond availability of stocks of resources, what are the planetary boundaries within which our consumption should be restrained in order to support sustainability.

Mont *et al.* (2013) estimate a sustainable per capita consumption of resources would be around 8 tonnes.

Some have sought to estimate what a sustainable per capita level of resource use could look like. For instance, Bringezu (2015) proposed a material footprint of 5-10 tonnes per capita while O'Neill *et al.* (2018) propose a 'per capita boundary' of material use of 7.2 t y^-1^.

Assume that a 'sustainable' level of global per capita resource use today might be between 5-10 tonnes. Accounting for the impact of future population growth on this by assuming technology will counteract it.... Assuming a level of GDP of GBP 4 trillion in 2050, achieving a sustainable per capita level of resource use in 2050 of 5 tonnes would require reducing RMC by X times, equating to an increased RP by X relative to 2017 figures, while achieving a per capita level of resource use of 10 tonnes would require RP increasing by X.

IRP will be publishing report 'Defining Sustainable Levels of Resource Use (2021)

Bringezu ([2019](https://www.mdpi.com/2079-9276/8/3/140))

**Resource use**

In physical terms, depreciation of renewable resources arises when:

*R \> g*

Where *R* is the rate of resource use and *g* is the natural growth/renewal rate of the renewable asset in question, while overuse of non-renewable resources arises when:

*R \> 0*

Where *R* is the rate of resource use, implying that any level of resource use greater than 0 might be understood as unsustainable given non-renewable capital cannot, by definition, be replenished at an equal rate within a meaningful timeframe for an individual human.

**Waste production**

In physical terms, environmental overuse as a result of anthropogenic waste production arises when:

*E \> A*

Where *E* is emissions of waste residuals and *A* is the assimilative capacity of the receiving environment.

Beyond the general prescription that current levels of primary material use in industrialised countries is likely greater than a sustainable level (Bleischwitz, ), quantifying more precisely what a 'sustainable' level of resource use might look like has proven difficult. The environmental science around resource use is currently far weaker than that associated with the climate specifically. It therefore remains difficult to say with any degree of certainty, what might constitute a 'sustainable level of resource use' (Bleischwitz, ), least not due to differing interpretations of sustainability. Complicating the matter is the fact that environmental impacts vary by material type, and thus not only overall tonnages but also the composition of material use must be considered (unlike for globally intermixing gasses such as carbon dioxide), while in addition, the environmental intensity of resource use can be moderated by technologies of extraction and production which may improve with time. Notwithstanding the significant uncertainty associated with such estimates, several authors have sought to estimate what an acceptable level of material extraction globally might be, variously accounting for the potential resource and waste-related environmental limits. Dittrich et al. (2012), for instance, suggest that global material extraction should not exceed 50 Gt y-1, about half the level evident today and equating to a global per capita limit of 8 tonnes y-1 by 2030. This level was echoed in a separate analysis by Hoekstra and Wiedmann (2014) and Mont et al. (2013) in O'Neill et al. 2018. UNEP's International Resource Panel (IRP) recommends a per capita target of between 6 and 8 tonnes y-1 by 2050 (2014). Bringenzu (2015) based on a higher population growth projection than that used in the IRP study, suggests a per capita target value of 5 tonnes for the year 2050, with a range of 3-6 tonnes (based on returning to year 2000 material use of 50.8 Gt).

Bringezu (2019) -- it has been suggested to limit the cropland required for final consumption of agricultural goods to 0.20 ha/person in 2030, corresponding to 0.16 ha/person in 2050 in order to halt the loss of global biodiversity by land use change.

## Gross Domestic Product

The historical roots of national accounting span back to determining the tax base of nations in the times of the Domesday Book (1085-86) and possibly earlier. Petty (1665) and King (1695) produced some of the first estimates of national income in Europe ([Maddison, 2003](http://www.ggdc.net/maddison/articles/colin_clark.pdf); [Vanoli, 2016](https://ec.europa.eu/eurostat/cros/system/files/p1-national_accounting_at_the_beginning_of_the_21st_century.pdf)). However, such estimates were produced intermittently and in a largely unstandardised way. National accounting in its modern-day form was introduced from the 1920s, pioneered by Kuznets in the USA and Clark in the UK to support macroeconomic policy aimed at mobilizing economic resources following the Great Depression and leading into World War 2. The System of National Accounts (SNA) - an internationally agreed standard set of recommendations on how to compile measures of economic activity - was introduced by the United Nations (UN) in the 1950s to support international comparability of the statistics countries were collecting. Most countries now compile statistics about their economy in accordance with the UN-SNA which represents a rigorous accounting framework (Malinvaud, 1973).

Gross domestic product (GDP) *'combines into a single figure...\[the monetary value of\] the \[market\] output...carried out by all the firms, non-profit institutions, government bodies and households in a given territory during a given period, provided that the production takes place within the country's economic territory'* ([OECD, 2014, p.15](http://www.oecd.org/sdd/UNA-2014.pdf)). GDP is a headline measure of the SNA and the most widely used metric for measuring national economic development at present.[\[1\]](#_ftn1) Reference to economic growth today is generally in reference to the level of output in an economy relative to prior years as measured by inflation-adjusted GDP. Growth in GDP is frequently an implicit, if not explicit, target that national governments subscribe to.

Economic value can be understood as being created through production activities, with 'value added' what remains after the costs of production are accounted for, from which income e.g. wages or share dividends is derived. This income is then either spent or saved as financial or non-financial assets and in some cases re-lent back into the economy. Under the production approach, GDP at market prices is equivalent to national gross value added (GVA) - which is a measure of the increase in the value of the economy due to the production of goods and services - plus taxes and less subsidies, as so:

Where *VA* refers to value added across all firms, *t* is tax and *s* is subsidies. As a sum of expenditures on final goods and services by final users, GDP can alternatively be written as:

Where *C* is consumption (or expenditure in the economy on things the National Accounts categorises as consumption), *I* is investment (expenditure on domestic investment), *G* is expenditure by Government, *X* is the monetary value of exports and *M*, that of imports. GDP can lastly be calculated under the income approach, as the sum of primary and secondary income, compensation of employees and taxes and subsidies.

Economic production involves the variably consumptive conversion of production factors or capital stocks into income. Conceptually, economic welfare broadly constitutes the difference between the benefits and costs of such economic activity (Lawn, 2014). Economic growth as measured by change in GDP can be argued to be associated with an expansion in opportunities for material welfare given higher purchasing power and correlation with employment, thereby allowing people to: 1) buy goods and services providing welfare directly; and 2) pay taxes, enabling the state to provide public goods. The use of GDP as a proxy of economic welfare and for guiding societal development therefore has some key benefits, including a fit with the economic definition of preference satisfaction through consumption and the correlation that exists between per capita GDP and certain socially desirable outcomes such as reduced infant mortality and increased life expectancy.

There are nevertheless several significant issues with the use of GDP as an effective indicator of societal development by itself. Kuznets himself recognised this, famously saying *'the welfare of a nation can scarcely be inferred from a measurement of national income'* (1934). Issues with GDP identified include:

1.        Using market prices as an indication of economic welfare is hampered by price distortions arising from monopoly, taxation, poor information and market imperfections;

2.        The reliance on market prices and therefore on tracking market transactions means that many welfare benefits are overlooked altogether e.g. non-marketed household production, leisure or volunteer services which don't lead to the production of goods. GDP therefore can be seen to represent a narrow conception of welfare;

3.        The national accounts may mismeasure nominal GDP arising from new services such as those linked to the digital economy and not capture consumer surplus associated with such new services and quality-improved goods and services very effectively ([Dynan and Sheiner, 2018](https://www.brookings.edu/wp-content/uploads/2018/08/WP43-8.23.18.pdf));

4.        GDP is not able to distinguish between production activities which contribute to economic welfare and those that reduce it, with the result being that economic income is not always correlated with economic welfare at a societal level;

5.        As a 'gross' measure, GDP does not account for depreciation in underlying capital stocks on which economic activity is reliant. An insensitivity to depreciation in capital assets (whether produced or natural) which are central to long-term income, means GDP is poorly suited to telling us about the likely sustainability of income flows in the long-run. Indeed, focusing on maximizing GDP in the short-term can actually provide an incentive to deplete the capital stocks which underpin future human income as current returns are not considered alongside the opportunity cost to future output[\[2\]](#_ftn2) ([Dynan and Sheiner, 2018](https://www.brookings.edu/wp-content/uploads/2018/08/WP43-8.23.18.pdf));

6.        Aggregate measures of the national accounts such as GDP or the widely used measure of GDP per capita, do not provide insight into the distribution of income across society and may give an inaccurate picture of average welfare if income is unequally distributed.

There has been some disagreement at the margins around whether the use of GDP as a headline metric for economic development is warranted, with some commentators supporting the use of Gross National Income (GNI) instead on the basis of it providing an improved indicator of the monetary resources actually available to those who live in a country, while others support the use of Gross National Disposable Income (GNDI) as a better indicator of the money actually available for consumption and saving activities. GNDI also includes both net factor income (captured by the GNI) as well as unilateral transfers, making it particularly relevant as a measure of interest for developing countries ([Capelli and Vaggi, 2013](https://ideas.repec.org/p/pav/demwpp/demwp0062.html#:~:text=Gross%20Domestic%20Product%20(GDP)%20is,who%20live%20in%20a%20country.)).

Given the perceived breadth of issues identified with GDP however, some of which are outlined above, and galvanised at an international level by the 1992 Earth Summit, there has been a push to develop quite significantly different measures of societal development altogether to GDP.

Stiglitz, Sen and Fitoussi (2009) in a seminal review undertaken at the request of the then President of France, Nicolas Sarkozy, argued that society not only needs to be steered by a more comprehensive measure of economic and societal progress than GDP, but also that no single composite measure could summarize something as complex as the magnitude and sustainability of the welfare of members of society. The review instead proposes countries use a dashboard of indicators which:

1.        Expand the measure of human welfare to cover material welfare, health, education & knowledge, quality of personal activities including work, degree of involvement in political & social life and environmental quality. Expanded welfare measures generally look to capture and track contributions to human wellbeing outside of economic income e.g. health or education without the benefits of these necessarily needing to be captured within increased output or income;

2.        Incorporate a measure of income distribution e.g. using median rather than mean incomes; and

3.        Measure change in underpinning capital stocks e.g. natural, built and human capital on which welfare is reliant.

We outline just a few of the many alternative measures to GDP which have been proposed below. These are broadly arranged into those seeking to alter or augment the SNA and its headline measures in some way, and those proposed largely outside of the SNA.

### Developments within the System for National Accounts

Incorporating information on natural assets into standard accounting frameworks is argued to be essential by some in order to mainstream environmental information and broaden the evidence base for economic decisions (Obst and Vardon, 2014; Solow, 1993). Since the 1980s, the SNA has been augmented in two main ways to attempt to account for sustainability concerns ([Spash, 2000](https://www.clivespash.org/eve/PRB9-edu.pdf)):

1.        By expanding the national accounts to include environmental data sets through Satellite Accounts; and

2.        By seeking to correct SNA aggregate measures such as GDP to take fuller account of the depletion of natural resources and the deterioration of environmental functions.

#### Indicators supplementing GDP

#### Capital accounting[**\[3\]**](#_ftn3)

GDP and other aggregate indicators of the national accounts are flow rather than wealth measures. National accounts are increasingly composed of balance sheets. Hamilton and Naikal (2014) categorise total societal wealth into produced, natural and intangible capital, with the latter an aggregate including human, social and institutional capital, generally calculated as a residual in assessments of wealth after the value of other inputs are accounted for. The World Bank (2010) find tangible assets only account for a relatively small proportion of total wealth (in money value) across all countries while intangible assets make up 60-80% of wealth across countries. Types of capital stocks include:

•         **Natural capital** - The stock of renewable and non-renewable elements of the natural world (e.g. plants, animals, air, water, soils, minerals) that separately or in combination, yield a flow of benefits (use, option and non-use values) to people, and which can otherwise be depreciated by pollution and overuse, conserved and invested in through restoration. Ecological landscapes are the 'basic unit of most ecological processes and the goods and services derived from them' (Barbier 2015, p.26). The derivation of value from the natural world often relies on other types of capital for transformation into goods and services;

•         **Built capital** - Material goods or fixed assets e.g. buildings, infrastructure and machinery which contribute to the production process rather than being the output itself e.g. tools, machines, buildings (the SNA already measured change in these assets);

•         **Human capital** - The human capacities to transform tangible assets into outputs through endowments of education, specific knowledge and the wider abilities and qualities of people that make them productive (Becker; Dawson & Martin, 2015). Julian Simon, for example, argued the ultimate resource was the human mind;

•         **Social and institutional capital** - Factors such as the quality of institutions, rule of law, governance, and the relationships between people in the form of networks, norms and trust which work to lower transaction costs and support innovation (Maskell, 2002);

•         **Health capital** - Arrow *et al.* (2010) find the value of "health capital" is significant relative to other forms of capital, however this is generally not a category reflected widely in studies of wealth; and

•         **Financial capital** - Used as a store of value and enabler of exchange. The most fungible form of capital and often an essential enabler of production alongside those other forms of capital outlined, though only as valuable as shared perceptions of its worth.

To better account for changes in natural capital and economic-environment relations, the SNA was added to by the satellite UN System of Environmental-Economic Accounts-Central Framework (SEEA-CF) in 2012, which consists of:

1.        **Asset Accounts** -- estimating the physical and monetary value of stocks of natural resources;

2.        **Physical Flow Accounts** -- showing how the environment contributes to the economy via physical flows e.g. through the extraction of raw materials as captured in the Environmental Accounts, the impacts that the economy has on the environment for instance through air emissions as captured in the Atmospheric Emissions Accounts and other residual flows e.g. solid waste.; and

3.        **Environmental-Activity Accounts** - showing how society responds to environmental issues through environmental protection e.g. taxation and resource management expenditures. When such tax data is combined with physical data at a national or industry level, it is possible to see whether increasing taxes has an effect on environmental performance over time.

The SEEA-CF physical flow accounts are consistent with the economic flows data produced by the SNA, making it possible to link economic developments e.g. output and value added, to natural resource inputs and generation of residuals as well as expenditure data ([Hoekstra, 2020](https://seea.un.org/content/how-natural-capital-accounting-contributes-integrated-policies-sustainability)).

The SEEA-CF focusses on environmental flows that are separable. To consider more systemic changes in ecosystem conditions, the SEEA-CF was added to by the SEEA-Experimental Ecosystem Accounts (SEEA-EEA) in 2013. The SEEA-EEA provide a spatially explicit approach to quantifying changes in ecosystems through GIS mapping of the extent and condition of ecosystems. The modelling tool [ARIES](https://aries.integratedmodelling.org/aries-for-seea-explorer/) have been developed to lower the barriers to compiling these complicated datasets via tools such as machine reasoning.

[Natural Capital Accounts](https://www.ons.gov.uk/economy/environmentalaccounts/bulletins/uknaturalcapitalaccounts/2020) (NCA) differ to the Environmental Accounts (EA) by summarising the physical annual flows of services provided by the natural environment rather than the pressures placed on the environment. In some instances, the two accounts mirror one another e.g. in the case of oil extraction, the use of these as an input into economic activities recorded in the EA equals the supply of provisioning services of oil from natural capital as recorded in the NCA. In other cases however, the relationship is not as direct (Bright *et al.* 2019). The NCA also attempts to track the waste remediation services that nature provides to people in the UK e.g. via the sequestration of pollution as well as flows of cultural services derived by people.

With significant developments in the SEEA and SEEA-EEA in the last decade, the technical push to develop natural capital accounts has proceeded largely independent of the pull of policy makers for a long time, however increasingly, barriers to considering environmental factors through the SNA is not a wholesale lack of data but rather the lack of awareness of available data and mainstreaming of this as a means of assessing policy questions (Vardon, Burnett and Dovers, 2016). Valuation of assets is largely done on a domestic basis, however there is a place for the further development in linking degradation of natural capital assets to consumptive pressures ([Argawala, 2019](http://etheses.lse.ac.uk/4146/1/Agarwala__Natural-capital-accounting.pdf)), as has been done for consumption-based emissions and material flow accounting (e.g. Owen *et al.* 2020).

The Inclusive Wealth Index (IWI) most recently put forward in the Dasgupta Review (2021), proposes that countries track the aggregate value of all capital assets as a better indication of economic progress than GDP, with increases in inclusive wealth indicating an improved productive base capable of supporting living standards into the future, and decreasing values, the opposite. The weak sustainability grounding of the indicator through its implicit acceptance of growth in non-natural capital being able to offset losses in natural capital is illustrated in the findings of the 2012 Inclusive Wealth Report, which suggested that across the twenty countries measured using the IWI, human capital growth was found to offset declines in natural capital, while technological innovation and oil capital gains outweighed declines in other natural capital and damage from climate change.

A growing number of countries have developed expanded national balance sheets, though issues with the natural capital accounts compiled by national governments include:

1.        Accounts in their current form are incomplete and thus limited by a lack of comprehensiveness e.g. omitting the value of soils and biodiversity, which is to a large extent due to disagreement over methodologies for measuring such assets but also data gaps; and

2.        Monetary valuation of stocks are highly influenced by anticipated future values which are generally based on current rents. These valuations can therefore be subject to significant volatility depending on changes in the market, and ultimately human perception.[\[4\]](#_ftn4)

#### Indicators adjusting GDP

#### Genuine Savings

As an example of a adjusted aggregate indicator, the measure of 'genuine savings' (GS) developed by Pearce and Atkinson (1993) attempts to link wealth accounting to flow measures of savings within the SNA, building on the stock-flow view of the economy found in Fisher (1911), Hicks (1939) and Samuelson (1961). The metric effectively incorporates an empirical expression of the Hartwick Rule and is thus grounded in weak sustainability theoretics. GS, otherwise referred to as 'adjusted net savings' within the UN Central Framework as well as by the World Bank, is an attempt to build on, but redefine, the methodology of 'adjusted net national income' (ANNI). ANNI itself modifies 'net national income' (NNI) (i.e. 'gross national income' (GNI) adjusted for consumption of fixed capital[\[5\]](#_ftn5)) to further account for depreciation in natural capital[\[6\]](#_ftn6) to estimate the income available for current consumption or alternatively investment to support future consumption.

GS as a savings rather than income measure, alternatively adds to a country's gross savings its educational expenditures and subtracts from this the value of fixed capital depreciation, natural resource depletion for a variety of resources and some pollution-damage costs. GS is presented as a percentage of GNI, with a negative GS representing a nation unsustainably drawing down its wealth by saving insufficiently, thereby impinging on the potential for future welfare. GS can be written in notation as:\
\

Where *GrS* is 'gross savings' i.e. GDP minus consumption expenditure, from which depreciation in produced capital (*PC*) is subtracted to arrive at 'net savings', added to which is the change in human capital (*HC*) proxied by educational expenditure. Following this, a subtraction of the depletion of non-renewable resources (energy and materials) (*NR*) and net deforestation (*ND*) is undertaken to arrive at 'depletion adjusted savings', with a final further subtraction of damages from CO2 and particulate matter (*D*) made to estimate GS.

When interpreting the indicator, if GS \< 0, then development is deemed unsustainable. The indicator therefore guides a country to either reduce levels of capital consumption or increase capital investment to the point where GS equals 0 or greater. GS has been evidenced in several assessments as robust, for instance, historically co-integrating with future consumption in the US, Britain and Germany (Hanley *et al.* 2016), though not across all studies (Ferreira and Vincent, 2005; Pezzey *et al.* 2006). Issues nevertheless identified include that GS:

1.        Is 'one sided', in that it can only reliably highly the occurrence of negative environmental performance because a non-negative GS might not guarantee sustainability if GS has been persistently negative in the past (Asheim 1994; Pezzey and Withagen, 1995);

2.        By bringing different types of capital stocks into the same measure and permitting an increase in one capital stock e.g. human capital to offset reductions in natural capital, biophysical limits to substitution seen by others as central to national sustainability issues might not be sufficiently captured;

3.        May be unable to correctly signal economic unsustainability in the event that environmental marginal-damage-curves relevant to an economy are characterized by non-linearities (Hamilton and Naikal 2014b); 

4.        Is limited in its comprehensiveness in measuring change in natural capital by omitting the value of changes in environmental stocks including fisheries, groundwater, soils and biodiversity (Dietz and Neumayer 2004) due to data gaps and areas of un-agreed methodology, as well as inconsistencies in the treatment of environmental externalities (Neumayer, 2000);

5.        The GS rule becomes more complex if the assumption of constant population is abandoned, with population growth negatively impacting sustainability once population growth is accounted for. GS therefore needs to be measured at a per-capita level for sustainable per capita welfare to be protected; 

6.        By being linked to standard accounting measures tracked at a national level, GS is not well suited to account for unsustainable pressures overseas from a population due to domestic consumption made possible through the occurrence of trade;

7.        Its accounting of human capital savings is incomplete as depreciation of human capital is not estimated (Hamilton, 2003).

### Developments outside of the SNA

#### Indicators replacing GDP

#### Expanded Welfare Measures

##### Genuine Progress Indicator

The 'genuine progress indicator' (GPI) attempts to track 'genuine' economic welfare arising through economic activity. GPI builds on Daly and Cobb's (1992) Index of Sustainable Economic Welfare (ISEW). It departs from an estimate of personal consumption adjusted for income inequality, after which further adjustments are made to attempt to distinguish utility-increasing expenditures on one hand from defensive expenditures (Daly and Cobb, 1989) and environmental damages (Vemuri and Costanza, 2006) on the other.

More specifically, the production of GPI involves adjusting personal consumption figures with economic indicators accounting for inequality, the timing of welfare benefits derived from durable consumer goods, the costs of unemployment and net capital investment within economic domains. Further adjustments are made to account for the costs of water, air and noise pollution, the loss of ecosystem services and the depletion of non-renewable ecosystem services within the environmental domain. For social aspects, an attempt is made to account for the value of work within the household, costs of family changes and crime, commuting and loss of leisure time as well as the value of volunteering and higher education (Lawn, 2014).

A key insight of the ISEW and GPI identified by Max-Neef (1995) is that beyond a point, per capita GDP stops being correlated with per capita GPI, and additional welfare benefits from GDP growth are limited or negative. While comprehensive in its measurement, GPI has been critiqued on the basis of:

1.        Not providing a rule by which to determine the sustainability of economic welfare (Neumayer, 1999; Dietz and Neumayer, 2007; Harris, 2007);

2.        Assuming replacement costs increase over time, which is likely erroneous because, for instance, while replacement of hydrocarbons with renewable technologies e.g. solar might have been more expensive in the past, it has now got cheaper and may continue to do so through innovation; 

3.        Its treatment of the distribution of income which fails to command general agreement; and

4.        It assuming a compounding or cumulative environmental damage function (Neumayer, 2000) as per Daly and Cobb (1989), the value of which is measured in terms of the opportunity cost of a fund contributed to by the internalized externality of emissions. This has been argued to be an incorrect approach if marginal social cost (MSC) values are used given these already internalize accumulated costs. Removing this feature has actually been shown to negate Max-Neef's threshold effect (Neumayer, 2000). 

##### Human Development Index

The United Nations' Development Programme's Human Development Index (HDI) is a composite unweighted indices combining a measure of standard of living, health and education (proxied as per capita GDP, life expectancy at birth, and years of education for an average adult and the Gross Enrollment Index, respectively). The measure normalizes each variable to a scale of between 0-1 and averages across these using the mean (initially arithmetic and then geometric) to produce an annual value for a country. The Inequality-Adjusted measure of HDI goes further by discounting each dimension's average value according to the inequality of that value within the relevant population ([UNDP, 2020](http://hdr.undp.org/en/content/inequality-adjusted-human-development-index-ihdi#:~:text=The%20IHDI%20combines%20a%20country's,to%20its%20level%20of%20inequality.)). Issues identified with the measure of HDI and its variants include:

1.        That while it can offer a broader insight into the determinants of human development, it can not necessarily give insight into its sustainability, for which it would need to incorporate a mechanism for accounting for over-exploitation of resources ([Sagar and Najam, 1998](https://www.sciencedirect.com/science/article/abs/pii/S0921800997001687)); and

2.        HDI assigns weights to certain factors that imply equal trade-offs when these measurements may not always be equally valuable. For example, countries could achieve the same HDI through different combinations of life expectancy and GNI per capita.

##### **Jones and Klenow's Wellbeing Index**

Jones and Klenow propose an index combining data on consumption with three non-market factors---leisure, excessive inequality, and mortality--- to calculate expected lifetime economic benefits for a population over time. The index focusses on consumption rather than income, adding to this the value of leisure (or home production), and subtracting costs related to inequality. These adjustments are made within a utility function ([Jones and Klenow, 2016](https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.20110236)), with consumption weighted heavily within the index. This calculation measured across one year is then multiplied by the average life expectancy within a country to give a measure of average expected lifetime welfare adjusted for consumption, leisure, inequality and life-expectancy. The USA is used as a benchmark (i.e. =1) in the index, with all other countries' values measured in relation to this. Bannister and Mourmouras (2018) have sought to extend this work to include measures of environmental externalities based on global externality costs of GHGs through assuming a tax is applied to the population proportionate to the externality of global GHGs they emit. This is done in a partial manner by accounting for solely the costs of externalities on consumption, rather than across all measures making up the index such as life expectancy or leisure.

#### Subjective Wellbeing Measures

A rational understanding of welfare might justifiably be argued to need to incorporate subjective perspectives (Doyal and Gough, 1991). Easterlin (1974) observed that within a country, rich people tend to be happier than poor people, but across countries, rich nations tend not to be much happier than poorer ones. Welfare and wellbeing can be understood in *objective* terms i.e. the circumstances of a person's life such as income or life expectancy as well as in *subjective* terms i.e. the personal judgements of these circumstances people have, inclusive of their own perceived happiness and satisfaction. Happiness is a subjective evaluation of those objective circumstances, but with no universally accepted and used definition. This is reflected in the different ways happiness has sought to be measured, for instance:

1.        Current/remembered reported emotion elicited through questions such as 'how happy are you right now?';

2.        Cognitive life evaluations elicited through questions such as 'how happy are you with your life as a whole?';

3.        Eudaimonic happiness elicited through questions such as 'does your life have meaning and purpose?'

The link between income and subjective wellbeing is complex for reasons including that income is often a 'positional good', while people can adapt to increasing income levels. Subjective wellbeing measures have been expanded on within the 2018 HMT Green Book, however problems associated with the subjective wellbeing approach and basing policy on self-reported experienced utility include:

1.        Potentially flawed assumptions of interpersonal comparability;

2.        Measurement issues relating to the choice of scales and the influence of moods

[\<https://www.lse.ac.uk/PBS/assets/documents/SPCW-WELLBEING-FINAL.pdf\>](https://www.lse.ac.uk/PBS/assets/documents/SPCW-WELLBEING-FINAL.pdf)

#### Biophysical Indicators

Broadly, biophysical indicators as presented here are those which do not incorporate monetary valuation.

##### Material Flows

Modern societies require great quantities of different types of materials, some used in bulk, while others are highly specialized and are used in minute quantities (Hoekstra, 2020). Inspired by the work of Ayres and Knees (1969) on industry metabolism, studies of material flows apply the biological concept of metabolism to human society, utilizing quantitative assessment to describe or analyse these. Such studies generally depart from the view that the sheer scale of humanity's material use creates environmental problems and needs to be reduced accordingly (Daly, 1992). 'Resource Flow or Material Flow Analysis (MFA) can be considered as the application of the biological concept of metabolism to human society.' (Wiedmann *et al.* 2006). Material flow data is collected on a regular basis across a number of countries in accordance with the [Economy-Wide Material Flow Accounting (EW-MFA) framework](https://seea.un.org/sites/seea.un.org/files/global_material_flow_accounting_manual_final_draft.pdf) reflected in the SEEA-CF, meaning figures produced can be consistent with the principles and system boundaries of the SNA. Materials examined in material flow accounts are broadly categorised into biomass, fossil fuels, metal ores and non-metal ores.

In recent years, awareness of policy makers generally increased regarding the significance not only of materials and products directly used by a national economy, or a regional economy such as the EU, but also of indirect resource use required along supply chains and embodied in internationally traded products. Therefore due to the nature of increasingly complex production supply chains, consumption-based measurement of material flows have become increasingly relevant and more widely developed, often drawing on economic data captured in the SNA as a means of reallocating material extraction. Issues with material flow accounting approaches include:

1.        Material flow accounting (MFA) generally focusses on flows of material resources, without sufficient consideration for other types of resources e.g. water. The virtual water concept, as an example, expands the remit of inquiry to other types of resources that society uses.

2.        From an ecological standpoint, an additive approach based purely on weight can be problematic as two forms of material throughput with different environmental profiles cannot meaningfully be compared on the basis of weight just because they can be expressed in that same unit. Environmentally-weighted material consumption (EMC) tries to account for this by using environmental impact coefficients derived from life cycle analysis to weight the unit of each material type by its environmental impacts (van der Vote *et al.* 2003). Others have sought to translate material extraction into measures of areal extent e.g. Maus *et al.* ([2020](https://www.nature.com/articles/s41597-020-00624-w)).

##### Ecological Footprint

"Footprint" calculations are a technique through which environmental pressures are

attributed to domestic demand. The ecological footprint reveals the amount of land and water (surface area) that is necessary to produce a certain consumption bundle. The ecological footprint (EF) defines national sustainability in terms of an EF which is either less than nationally available biocapacity, or less than an equal share of global biocapacity when presented on a per capita basis. The vector for comparison between supply and demand is surface area (Ceballos *et al.* 2005). EF has enjoyed fairly widespread use, being used in UN Development Program Human Development Reports and in Welsh Government sustainability goals, while it has been applied at a range of scales from communities and cities to the globe. The metric builds on earlier measures of the impact of humans on ecosystems such as Vitsouek's *et al.*'s (1986) Human Appropriation of Net Primary Production (HANPP). EF takes a consumption-based approach and is theoretically premised on a 'strong sustainability' interpretation by requiring that nations maintain non-declining levels of natural wealth through aligning consumption with planetary constraints (Daly 2005; Wackernagel *et al.* 2014). Methodologically, a nation's EF is calculated by converting its populations' demand for resources and functions including food, energy, and requirements for absorbing waste, into the area of land (global hectares) required to produce these sustainably given current technologies. This demand is then compared to the area of land that a nation actually has for producing those resources (i.e. its biocapacity) or if on a per capita basis, the global hectares available per person, with sustainability seen to arise if areal demand is equal to, or less than, supply. Issues identified with the EF as a measure of sustainable development include:

1.        The focus of comparison in terms of land area has been critiqued for lacking a biophysical basis in terms of understanding of thresholds (Blomqvist *et al.* 2013);

2.        It has been critiqued for lacking a socioeconomic dimension, though this might be justified given that the indicator foremostly defines economic sustainability in terms of adherence to environmental limits. To incorporate socioeconomic content, some authors e.g. Moran *et al.* (2008) have proposed looking at the Human Development Index and EF side-by-side, and requiring, for instance, that for a country to be sustainable that it's EF is no greater than biocapacity and HDI no less than 0.8;

3.        Empirically, the conversion to land area of various environmental demand has been critiqued in some instances. For instance, energy consumption has taken up half of the global EF, but this is contested e.g. due to a variable treatment of nuclear energy through time (Ayres, 2000);

4.        EF's aggregation of factors controlled by different policy areas can arguably provide limited signals as to where policy effort should most effectively be deployed to enhance societal sustainability, though some policy prescriptions can be teased from the indicator e.g. reducing consumption demands and increasing land efficiency; and

5.        Methodologically, aggregation flaws arise by applying the same average biocapacity yield for resources globally, such that a nation may incorrectly be shown to be overshooting biocapacity if its yields for a given resource are greater than average (Van Kooten and Bulte 2000).

##### Planetary Boundaries

The 'planetary boundaries' (PB) concept (Rockstrom *et al.* 2009) precursored by Opschoor's (1987) concept of 'environmental space' is an attempt to identify what a safe level of environmental use might be based on the view that at any point in time, there are limits to the degree of environmental pressure the Earth's ecosystems can withstand without irreversible damage to these and the life supporting processes they support. The PB concept is grounded in the view that some natural capital components measured in terms of regulating services are non-substitutable. The underlying message of the metric is to remain within these boundaries so as to not overstep tipping points, though translation into management targets is required (Bringezu, 2019).

[\<https://www.eea.europa.eu/publications/is-europe-living-within-the-planets-limits\>](https://www.eea.europa.eu/publications/is-europe-living-within-the-planets-limits)

#### Hybrid Indicators

##### Sustainability Gaps

Hueting's (1980) 'Sustainable National Income' (SNI) attempts to adjust national income for the technical and structural costs of meeting strong sustainability standards as well as defensive expenditures. A prerequisite is to establish states of ecosystem which maintain vital environmental functions. The 'Sustainability Gap' then refers to the difference between observed states of the environment or pressures causing natural capital assets to be at that non-optimal level and that threshold level consistent with strong sustainability (Ekins and Simon [1999](https://www.inderscienceonline.com/doi/abs/10.1504/IJSD.1999.004313)). The gap can be expressed in physical or monetary terms and reflects the level of reinvestment and change an economy needs to make to maintain, protect and restore ecosystems to the level required by society. Ekins and Simon in extending this work advise against calculating SNI using monetary valuation of the degree of change in the economy over time to reach sustainable levels of resource use due to significant non-marginal price changes ([Dietz and Neumayer, 2007](http://eprints.lse.ac.uk/3058/1/Weak_and_strong_sustainability_in_the_SEEA_%28LSERO%29.pdf)).

##### 'Doughnut' economics

Raworth's 'doughnut' (2017) has been proposed as a dashboard approach measuring national and global sustainability based on meeting human needs within the 'planetary boundaries' defined by Rockstrom *et al.* (2009). A 'just and safe' level of development is understood as the space between two concentric circles, the outer extent of which represents PB's that should not be surpassed given known assimilative and regenerative capacities, uncertainty and precaution, and the inner circle of which represents satisfying human needs as codified in the Sustainable Development Goals.

##### Gross Ecosystem Product

Gross Ecosystem Product (GEP) seeks to measure the total value of final ecosystem goods and services supplied to people in a given region annually (Ouyang *et al.* 2020). It brings together an assessment of biophysical production values of ecosystem goods and final services (regulating and cultural services, with supporting services implicitly valued (Boyd and Banzhaf, 2007) through physical accounting based on SEEA-EEA, with ecosystem service pricing based on market and non-market valuation to quantify, in monetary terms, the flow of services from ecosystems in a given period. Such an approach is valuable as ecosystems provide a crucial source of welfare to those marginally engaged in markets as well as to people in ways outside of the market e.g. via non-exchanged amenity values (Vedeld *et al.* 2004). GEP can be written as:

Where *EPV* is the economic value of ecosystem provision, *ERV* that of regulating services and *ECV* that of cultural services.

## Measuring Resource Use

There are a range of methodologies available for analysing material flows, the choice of which will affect final estimates. The most widely established methodological framework for measuring material resource flows at a national level is the Economy-Wide Material Flow Accounting (EW-MFA) system ([Eurostat, 2018](https://seea.un.org/sites/seea.un.org/files/ks-gq-18-006-en-n.pdf)) which underpins the SNA SEEA Material Flow Accounts (SNA-SEEA-MFA). The system seeks to standardise how material inputs to the economy, net additions of materials to stocks and outflows (disposal of waste and emissions and exports) are measured by national statistics offices in accordance with the mass balance principle (conservation of mass principle).

[\<http://sciencesearch.defra.gov.uk/Default.aspx?Menu=Menu&Module=More&Location=None&Completed=0&ProjectID=14064\>](http://sciencesearch.defra.gov.uk/Default.aspx?Menu=Menu&Module=More&Location=None&Completed=0&ProjectID=14064)

### Indicators

In a closed economy or at the global level, the sum of domestic resource extraction (DE) is equivalent to consumption-based material flow indicators such as domestic material consumption (DMC)[\[7\]](#_ftn7) or raw material consumption (RMC) as well as their equivalent input-based indicators e.g., direct material input (DMI)[\[8\]](#_ftn8) and Raw Material Input (RMI) as all trade flows net out.

The indicators total material consumption (TMC) and Total Material Requirement (TMR)[\[9\]](#_ftn9) expands the system accounting boundary by including unused flows. Input indicators illustrate all material inputs to the domestic economy, independent of whether products are consumed domestically or exported. As a result, these are not additive across countries in the manner consumption-based figures are, which conversely exclude the materials embedded in exports from a country.

Generally speaking, the broader the scope of the measure, the higher the potential uncertainty in the figures. EW-MFA consumption and input indicators track the same material resource flows which are categorised at a high level into biomass, metallic and non-metallic mineral resources and fossil fuels.

#### Domestic Material Consumption

Domestic Material Consumption (DMC) is a headline indicator derived from the EW-MFA and SEEA-CF-MFA systems. It is currently the most widely used material flow-based indicator at the core of national statistical reporting on material flows. DMC is calculated by summing the used fraction of domestically extracted and harvested materials and the weight of imported raw materials, semi-finished and manufactured products, while excluding the weight of exported raw materials, semi-finished and manufactured products.

DMC can therefore be written as:

Where *DE* is domestic extraction and *PtB* defines the physical trade balance of *Im* i.e. imports and *Ex* i.e. exports. DMC excludes hidden flows throughout. A closely linked indicator, Direct Material Input (DMI) is based on the same methodology but incorporates the materials mobilised or used in the production of exported goods and services ([OECD, 2008](https://www.oecd.org/environment/indicators-modelling-outlooks/MFA-Guide.pdf)).

Both DMI and DMC are weighted towards resource use activities within national boundaries and in that sense are more akin to 'production' oriented economic measures and similar to the manner in which UNFCCC accounting is undertaken for greenhouse gas emissions.

Key benefits of DMC and DMI include that their underlying methodologies are well documented, with national and official statistics largely drawn on in their compilation. This makes the compilation of their figures relatively transparent. The accuracy of these measures is also thought to be relatively high. A key issue with both indicators is referred to a problem of 'asymmetry'. That is, the weight of the traded components of material flows are based on the weight of goods crossing the border rather than the weight of raw materials used to produce those goods, contrasting with the treatment of domestic extraction. Where goods crossing the border are raw materials, this doesn't immediately pose an issue, however where the goods crossing borders through trade are finished or semi-finished products, this means there is a risk of systematic underestimation of the quantity of raw material extraction required to satisfy demand for import-intensive countries.

#### Raw Material Consumption

To capture the environmental implications of trade and increasingly globalised value chains, consumption-based accounting has sought to complement traditional production-based accounting ([Peters and Hertwich, 2008](https://www.sciencedirect.com/science/article/pii/S0048969720361167#bb0180)). Like DMC, indicators of raw material consumption (RMC) seek to measure domestic used material extraction, but in addition, also the full upstream used material extraction associated with the production of imports along their supply chains. Similarly to DMC, it excludes hidden flows throughout. Raw material input (RMI) is based on the same methodology but incorporates the raw materials mobilised or used in the production of exported goods and services.

A key benefit of using RMC over DMC is that it looks to measure both the weight of domestic extraction and overseas raw material extraction associated with the production of imports on an equal basis, rather than measuring imports based on the weight of materials and finished products crossing national borders. This is increasingly useful given the growth of complex international supply chains due to processes of specialization and cost-reduction seeking. By attempting to account for the indirect raw material 'rucksack' associated with imports, RMC and RMI may be subject to higher levels of uncertainty than indicators which focus on measuring materials directly used within the economy.

While there is ongoing work to harmonize methodologies for measuring RMC at an international level, the United Nations (UN) SNA-SEEA 2012 'Applications and Extensions' handbook states '*consumption-based indicators should be based on data and relationships contained in input-output tables; ideally...multiregional input-output tables should be used'* (page. 17).

## Coefficient Based Method

A method for estimating RMC developed by Eurostat works by applying 'raw material equivalents' (RME) to monetary import and export data using coefficients. In the context of EW-MFA, this approach was initially developed by the Wuppertal Institute in the 1990s. The approach can be written as:

Where *RME* refers to the raw material equivalents applied to each trade-related element of the formula and underlying elements are those which feed into a measure of national DMC. The material coefficients applied to the traded elements have been calculated using data from input-output tables, domestic extraction data from MFA and life-cycle-inventories. While an improvement over DMC by attempting to resolve the asymmetrical treatment between domestic extraction and traded components, the coefficient method struggles to accurately quantify materials associated with re-imported goods that cross borders several times, can have truncation errors (by not capturing the whole complexity of production chains so certain up-stream chains have to be "cut off". introduced when the full material supply chain is not accounted for, while conversion factors can be sourced from various years making inter-temporal comparison difficult ([Owen, Giesekam and Barrett, 2017](http://sciencesearch.defra.gov.uk/Document.aspx?Document=14321_ResourceEfficiencyMetrics.pdf)). This method has been applied to estimating UK-level RMC for approaching a decade ([Defra, 2011](http://ons.gov.uk/ons/rel/environmental/uk-environmental-accounts/2011---blue-book-update/artrme.pdf)).

##### Multi-Regional Input-Output Approach[\[LO6\]](#_msocom_6) 

NAMEA

Wiedmann et al. (2015) \[4\] defined the RMC as the "global allocation of used raw material extraction to the final demand of an economy . . .  which does not record the actual physical movement of materials within and among countries but, instead, enumerates the link between the beginning of a production chain (where raw materials are extracted from the natural environment) and its end (where a product or service is consumed)" (p. 6271).

Input-output economics was founded by the Russian-American economist Wassily Leontief (1936). Input-Output Analysis (IOA) play a central role in helping industrial ecologists understand which components of socioeconomic systems contribute to the extraction, transformation, use, and discard of natural resources to produce, reproduce, and operate their biophysical structures ([Wiedland *et al.* 2019](https://www.researchgate.net/publication/337155929_Supply_versus_Use_Designs_of_Environmental_Extensions_in_Input-Output_Analysis_Conceptual_and_Empirical_Implications_for_the_Case_of_Energy)). An Environmentally-Extended Multi-Regional Input-Output Table (EEMRIOT) table is an integrated dataset that combines two elements: a monetary input-output table (MIOT) representing monetary inter-industry flows and final demand, and an extension table in physical units depicting environmental flows associated with those economic activities ([Wiedland *et al.* 2019](https://www.researchgate.net/publication/337155929_Supply_versus_Use_Designs_of_Environmental_Extensions_in_Input-Output_Analysis_Conceptual_and_Empirical_Implications_for_the_Case_of_Energy)). One of the key data requirements for this approach is therefore national input-output tables which underpin the production of headline economic indicators such as GDP and are collected in accordance with the SNA. Another is the material flow accounts collected by countries in accordance with SNA-SEEA-CF guidance.

A method for calculating RMC has been developed by the University of Leeds (UoL) on behalf of Defra since 2017 and builds on a similar methodology for estimating the UK carbon footprint developed since 2008 ([Barrett, Owen and Sakai, 2011](http://randd.defra.gov.uk/Document.aspx?Document=FINALEV0466report(2).pdf)). It involves reallocating domestic extraction (as calculated through the SEEA and EW-MFA accounting system) by country and world region at a 15 category disaggregation, to final demand in the UK in a given year using a MRIO database underpinned by supply and use tables (SUTs)[\[10\]](#_ftn10) produced by the UK Office for National Statistics (ONS) and input-output tables compiled within the EXIOBASE MRIO database for trade data sourced from US COMTRADE alongside separate sources for material extensions. This approach usefully covers the whole economy in a systematic way, thereby avoiding truncation errors and double counting as different supply-chains are clearly distinguished from each other in the monetary input-output tables and allows for material inputs to re-imported goods to be more accurately measured. The methodology is extremely data intensive, requiring regular information on material extraction, production structures and international trade relations of trade partners ([Eisenmenger *et al.* 2016](https://www.sciencedirect.com/science/article/abs/pii/S0921800916302798)). Eisenmenger *et al.* ([2016](https://www.sciencedirect.com/science/article/abs/pii/S0921800916302798)) compared calculations of Austrian RMC for the year 2007 using 7 different approaches, with 4 of these MRIO and 3 hybrid life-cycle analysis-IO approaches. Results diverged significantly, with the spread of results between 21t/cap and 33 t/cap.

#### Total Material Consumption

Total material consumption (TMC) and its input-based equivalent, total material requirement (TMR) are metrics which expand the system boundaries of DMC and RMC to account for both used and unused extraction within a country in addition to used and unused extraction associated with upstream production activities associated with domestic consumption. Unused extraction includes the likes of mining overburden and bycatch from fishing. This measure is the most comprehensive out of those presented and viewed as most representative of overall environmental pressure ([Lutter and Giljum, 2014](https://one.oecd.org/document/ENV/EPOC/WPEI(2015)1/en/pdf); Kovanda, 2020), though is also associated with greatest uncertainty. TMR was calculated for the UK as part of the ONS Environmental Accounts up to 2013 ([ONS, 2013](https://www.ons.gov.uk/economy/environmentalaccounts/bulletins/ukenvironmentalaccounts/2013-06-26)).

### Comparing available resource use measures

Some general strengths and weaknesses for each measure of resource use currently tracked on a regular basis at a UK-level are set out in the table below.

## Measuring Resource Productivity/Intensity

"Intensity indicators compare trends in economic activity such as value-added, income or consumption with trends in specific environmental flows such as emissions, energy and water use, and flows of waste. These indicators are expressed as either intensity or productivity ratios, where intensity indicators are calculated as the ratio of the environmental flow to the measure of economic activity, and productivity indicators are the inverse of this ratio." (SEEA-Environment Extensions, 2012, pg. 13).

Both can be used to indicate decoupling, but conceptually different (productivity focussed on maximisation, efficiency focussed on the right level) and differ in their emphasis.

At its most basic, a measure of efficiency or productivity tells us about a relationship in terms of scale between an output and an input. Singular measures of resource efficiency/productivity (as opposite to combined measures e.g. total factor productivity) generally seek to track the effectiveness with which an economy or sub-national process uses resource inputs to generate material or service outputs or anthropocentric value of some description.

**Allocative efficiency** is a state of the economy in which production is aligned with consumer preferences; in particular, every good or service is produced up to the point where the last unit provides a marginal benefit to consumers equal to the marginal cost of producing.

Resource efficiency and productivity can be defined with respect to ([OECD, 2008](https://www.oecd.org/environment/indicators-modelling-outlooks/MFA-Guide.pdf)):

•         **Physical or technical efficiency** i.e. the quantity of a physical output in relation to a unit of resource input, with both expressed in physical terms (e.g. tonnes of crude steel produced in relation to a tonne of iron ore inputs). These may be desired outputs e.g. floor area or usable products or undesired outputs e.g. waste; (process level)

•         **Service efficiency** i.e. the quantity of a service or function e.g. km travelled per mass unit of material resource inputs for providing that service or function (MIPS); (meso-level)

•         **Economic efficiency/productivity** i.e. the money value of resources outputs relative to the money value of resource input(s) from either a cost-minimisation or benefit-maximization perspective; (process, meso and macro level)

•         **Economic-physical productivity** i.e. the money value of outputs per mass unit of material resource inputs. (macro level).

--         'Many authors treat both productivity and efficiency as the ratio between output and input, not indicating any difference between the two concepts (Sengupta 1995; Cooper et al. 2000). We define efficiency as the distance measure, that is, the difference between the actual ratio of inputs and outputs and the best possible combination of them. Efficiency and productivity, in any case, remain complementary concepts. Measures of efficiency are more accurate than those of productivity, as they involve a comparison with the most efficient combination, whereas productivity is based solely on the ratio of outputs to inputs (Daraio and Simar, 2007).' ([Toma, Massari and Miglietta, 2016](https://www.researchgate.net/profile/Pier-Paolo-Miglietta-2/publication/312296927_Natural_Resource_Use_Efficiency_and_Economic_Productivity/links/5878d61408ae8fce49325568/Natural-Resource-Use-Efficiency-and-Economic-Productivity.pdf)). - At a macro-level linked to the notion of allocative efficiency.

Other more complex multifaceted definitions: ''resource efficient development (...) allows the economy to create more with less, delivering greater value with less input, using resources in a sustainable way and minimising their impacts on the environment.'

At a national level, intensity indicators related to resource use are generally constructed by relating aggregate national economic output or value added to flow measures of resource input, both for the same time period, and are often presented as macro-economic concepts alongside labour or capital productivity (OECD, 2008). Tracking such a measure can help give insight into whether a country is decoupling economic output from resource use in a given year.

'Utilization of data on environmental flows. Commonly, information on environmental flows will not be strictly aligned to the measurement boundaries of the SEEA. Care should therefore be taken to record appropriately, with adjustment as necessary, entries for purchases abroad by tourists and re-exports. Careful attention should also be paid to the general issue of recording data on a residence basis rather than on a territory basis (see the SEEA Central Framework sect. 3.3, for details).' - MFA calculated on a territorial basis I think, while GDP on a residency basis

### Considerations around Indicator Structure

For efficiency measures related to resource use, an indicator can either be structured as a ratio with material use a denominator and value output a numerator such as with resource productivity, or alternatively structured with material use as a numerator and a measure of output as a denominator such as with resource efficiency. There are differences in emphasis and connotations between these two presentations. While productivity is frequently presented as a ratio, translating resource use into monetary terms based on foregone future values and current and future environmental damages in monetary terms, would allow for a measure of productivity derived through subtracting costs from aggregate output. Such an approach might align more closely with economic theory and weight material consumption impacts in welfare terms.

### Possible Output Indicator for an Efficiency Target

An output indicator component of a resource-related efficiency measure might be selected to represent:

1.        A desired output the indicator developer perceives society should be pursuing; or

2.        Something that is currently pursued in society and which the indicator developer wishes to see a decoupling of resource demands from.

There is a fundamental question in an efficiency measure regarding whether we are trying to actively steer society through both the denominator and numerator. It is also important to consider statistical coherence between the output and input measure, i.e. the degree to which they are logically connected and mutually consistent. While GDP includes final domestic demand and revenues from net exports in monetary terms, DMC includes domestic extraction and physical-net imports, reflecting that trade in materials and money, move in opposite directions (Eisenberger *et al.* 2016).

This chapter has identified some of the issues associated with GDP as a measure of economic welfare and wellbeing more generally, as well as some of the reasons it has remained so prominent as a metric guiding society over the last century. This prominence, even in the context of significant criticism of the metric may be a basis for justifying its use as an output metric within a measure of resource productivity. Using a headline measure of the SNA such as GDP which is widely recognised and pursued even if undesirable in some regards, accepts that society is pursuing this but nevertheless says, you can only continue to pursue this if you decouple it from resource use. There is a risk around whether incorporating a measure such as GDP may lead to redundancy in the metric over time if GDP becomes less of a focus over time for society. We might alternatively wish to use a measure we view as a more desirable output or outcome, but there might be some issues with this.

The output indicator, where relevant, can be normalised e.g. GDP placed on a per capita basis (usually taken as the standard of living), with median rather than average values used to potentially better account for distribution, or GDP adjusted based on a measure of inequality such as the Gini Coefficient and as included in the measure of HDI, though there are concerns with such an approach too e.g. Nolan ([2019](https://www.inet.ox.ac.uk/publications/no-2019-05-the-median-versus-inequality-adjusted-gdp-as-core-indicator-of-ordinary-household-living-standards-in-rich-countries/)).

## An Absolute vs. Efficiency Target

Some of the pros and cons of resource-use related targets levied in absolute terms e.g. a reduction in tonnages by a given date compared to efficiency targets e.g. a reduction in the material intensity (per capita or per unit of output) is given.

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Absolute                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Efficiency                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| •         Gives more certainty regarding outcome                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | •         Focus on decoupling of welfare from resource use. Increases in productivity are a precondition for saving resources without reducing the standard of living of people                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| •         Has the potential to still deliver improvements in resource productivity but while ensuring absolute decoupling                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | •         May allow us to hedge our bets as we work out how to decouple welfare from resource use and the indicator stabilises.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| •         Could limit achievement of other key environmental targets e.g. net zero                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | •         Policies that improve resource efficiency might be able to achieve decoupling, but higher resource efficiency might also boost economic growth and resource consumption as it shifts the macroeconomic production frontier and increases consumer income.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| •         There is uncertainty around the optimal level of resource use to reach. Notwithstanding the significant uncertainty associated with such estimates, several authors have sought to define what an acceptable level of material extraction globally might be, variously accounting for the potential resource and waste-related environmental limits. Dittrich et al. (2012), for instance, suggest that global material extraction should not exceed 50 Gt y-1, about half the level evident today and equating to a global per capita limit of 8 tonnes y-1 by 2030. This level was echoed in a separate analysis by Hoekstra and Wiedmann (2014) and Mont et al. (2013) in O'Neill et al. 2018. UNEP's International Resource Panel (IRP) recommends a per capita target of between 6 and 8 tonnes y-1 by 2050 (2014). Bringenzu (2015) based on a higher population growth projection than that used in the IRP study, suggests a per capita target value of 5 tonnes for the year 2050, with a range of 3-6 tonnes (based on returning to year 2000 material use of 50.8 Gt). | •         Of the 27 EU Member States whose resource productivity improved between 2000 and 2017, 12 have experienced an increase in demand for materials over the same period. In some cases, the increase was substantial: Malta 71 %, Estonia 70 %, Lithuania 63 %, Bulgaria 46 %, Luxembourg 34 %, Poland 33 %, Slovakia 32 % and Sweden 31 %. In general, policies and targets for reducing overall material use are far less common than those aimed at increasing resource productivity ([EEA, 2018](https://www.eea.europa.eu/airs/2018/resource-efficiency-and-low-carbon-economy/resource-efficiency))                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|             Bringezu (2019) -- it has been suggested to limit the cropland required for final consumption of agricultural goods to 0.20 ha/person in 2030, corresponding to 0.16 ha/person in 2050 in order to halt the loss of global biodiversity by land use change.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | •         Rebound effects - Economic theory shows that growth occurs when an economy becomes more efficient, in the sense that production processes require fewer resources to achieve the same or greater levels of output. In the long run, these "productivity" improvements lead to increases in national income which are used for purposes such as buying products or services, or investing in natural capital. Uncertainty in the level of resource use it will deliver even if the target is met. Technological progress can and does raise resource productivity. But for larger systems under conditions of economic growth and stable (or even declining) resource prices usually rebound effects occur that (out)balance those productivity gains -- thus the resource use of the larger system, despite resource productivity gains, remains the same or even rises. (Alcott 2005; Ayres et al. 2007; Binswanger 2001; Holm and Englund 2009; see: Jevon' s paradox: Polimeni and Alcott 2008).' |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| •         Potential for significant welfare impacts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | •         However increases in growth are not unbounded (can only go as high as the costs of resources)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | •         "If GDP increases at a quicker pace than resource consumption, then mechanically GDP/DMC increases. This would be considered as a progress. But European resource consumption could still increase in absolute terms (way beyond what is sustainable), which would be a failure. Therefore such an aggregated indicator would hide a negative trend for the absolute resource consumption of Europe -- which is THE main sustainability issue." (WWF, 2012)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Bringezu (2015) argues that material flow related targets should be based on the perspective of a future metabolic system that can operate within the global bio-geo-sphere for centuries to come, and this therefore implies the need for an understanding of the implications of material flows for the bio-geo-sphere and limits to these within understood thresholds. Beyond the general prescription that current levels of primary material use in industrialised countries is likely greater than a sustainable level, quantifying more precisely what a 'sustainable' level of resource use might look like has proven difficult. The environmental science around resource use is currently far weaker than that associated with the climate and it therefore remains difficult to say with any degree of certainty, what might constitute a 'sustainable level of resource use' (Bleischwitz, ). Complicating the matter is the fact that environmental impacts vary by material type, and thus not only overall tonnages but also the composition of material use must be considered (unlike for globally intermixing gasses such as carbon dioxide), while in addition, the environmental intensity of resource use can be moderated by technologies of extraction and production which may improve with time. Fischer-Kowalski *et al.* (2010) argue that 'even if estimates of capacity limits are uncertain and some degree of substitution and capacity expansion is assumed, by many measures humanity has already exceeded environmental carrying capacity.

New report published as part of 2 year programme on Circular Economy Taskforce entitled 'why the UK needs a new vision for resource use'. Pushing for a halving of resource use by 2050. Argues for needing a clear vision on: 1) incentives; 2) products; 3) behaviours; 4) business models; 5) logistics; and 6) infrastructure similar to carbon management. For carbon, there is a clear vision, budgets, legally binding targets and input from the CCC. Argues that the following is needed: 1) Target for cutting resource use; 2) Plans for specific sectors and materials; and 3) Binding interim goals
:::
